# Generated by Django 5.1 on 2025-07-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'constraints': [models.UniqueConstraint(fields=('descricao',), name='indicadores_unique_descricao', violation_error_message='Descrição é unico em Indicadores')],
            },
        ),
    ]
