# Generated by Django 5.1 on 2025-07-16 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadoresValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano Referencia')),
                ('mes_referencia', models.IntegerField(choices=[(1, '01 - Janeiro'), (2, '02 - Fevereiro'), (3, '03 - Março'), (4, '04 - Abril'), (5, '05 - Maio'), (6, '06 - Junho'), (7, '07 - Julho'), (8, '08 - Agosto'), (9, '09 - Setembro'), (10, '10 - Outubro'), (11, '11 - Novembro'), (12, '12 - Dezembro')], verbose_name='Mes Referencia')),
                ('data_inicio', models.DateField(verbose_name='Data Inicio')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('primeiro_dia_util', models.DateField(verbose_name='Primeiro Dia Util')),
                ('primeiro_dia_util_proximo_mes', models.DateField(verbose_name='Primeiro Dia Util do Proximo Mês')),
                ('dias_uteis_considerar', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Dias Uteis Considerar')),
                ('dias_uteis_reais', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Dias Uteis Reais')),
                ('valor_meta', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Meta')),
                ('valor_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Real')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='dashboards.indicadores', verbose_name='Indicador')),
            ],
            options={
                'verbose_name': 'Indicador Valor',
                'verbose_name_plural': 'Indicadores Valores',
                'constraints': [models.UniqueConstraint(fields=('indicador', 'ano_referencia', 'mes_referencia'), name='indicadoresvalores_unique', violation_error_message='Indicador, Ano e Mes de referencia são unicos em Indicadores Valores')],
            },
        ),
    ]
