# Generated by Django 5.1 on 2025-07-17 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_indicadoresvalores'),
        ('home', '0074_alter_jobs_sigla'),
        ('rh', '0038_afastamentos_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetasCarteiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_meta', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Meta')),
                ('valor_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Real')),
                ('considerar_total', models.BooleanField(default=False, verbose_name='Considerar Valores no Total')),
                ('indicador_valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='dashboards.indicadoresvalores', verbose_name='Indicador Valor')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.funcionarios', verbose_name='Responsavel')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.vendedores', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Meta Carteira',
                'verbose_name_plural': 'Metas Carteiras',
                'constraints': [models.UniqueConstraint(fields=('indicador_valor', 'vendedor'), name='metascarteiras_unique', violation_error_message='Indicador e Vendedor são unicos em Metas Carteiras')],
            },
        ),
    ]
