# Generated by Django 5.1 on 2025-07-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_indicadoresperiodos'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='indicadoresperiodos',
            name='indicadoresperiodos_unique',
        ),
        migrations.RemoveField(
            model_name='indicadoresperiodos',
            name='indicador',
        ),
        migrations.AddConstraint(
            model_name='indicadoresperiodos',
            constraint=models.UniqueConstraint(fields=('ano_referencia', 'mes_referencia'), name='indicadoresperiodos_unique', violation_error_message='Indicador, Ano e Mes de referencia são unicos em Indicadores Periodos'),
        ),
    ]
