# Generated by Django 5.1 on 2025-07-17 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_remove_indicadoresperiodos_indicadoresperiodos_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='indicadoresvalores',
            name='indicadoresvalores_unique',
        ),
        migrations.RemoveField(
            model_name='indicadoresvalores',
            name='ano_referencia',
        ),
        migrations.RemoveField(
            model_name='indicadoresvalores',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='indicadoresvalores',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='indicadoresvalores',
            name='dias_uteis_considerar',
        ),
        migrations.RemoveField(
            model_name='indicadoresvalores',
            name='dias_uteis_reais',
        ),
        migrations.RemoveField(
            model_name='indicadoresvalores',
            name='mes_referencia',
        ),
        migrations.RemoveField(
            model_name='indicadoresvalores',
            name='primeiro_dia_util',
        ),
        migrations.RemoveField(
            model_name='indicadoresvalores',
            name='primeiro_dia_util_proximo_mes',
        ),
        migrations.AddField(
            model_name='indicadoresvalores',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='dashboards.indicadoresperiodos', verbose_name='Periodo'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='indicadoresvalores',
            constraint=models.UniqueConstraint(fields=('indicador', 'periodo'), name='indicadoresvalores_unique', violation_error_message='Indicador e periodo são unicos em Indicadores Valores'),
        ),
    ]
