# Generated by Django 5.1 on 2025-12-10 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0082_responsaveis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('coluna', models.IntegerField(default=0, verbose_name='Coluna')),
                ('altura', models.IntegerField(default=0, verbose_name='Altura')),
                ('tipo', models.CharField(choices=[('pilha_rack', 'Pilha de Rack'), ('porta_pallet', 'Porta Pallet'), ('prateleira', 'Prateleira'), ('chao', 'Chão')], max_length=20, verbose_name='Tipo')),
                ('tipo_produto', models.CharField(choices=[('produto_acabado', 'Produto Acabado'), ('materia_prima', 'Materia Prima')], max_length=20, verbose_name='Tipo de Produto')),
                ('prioridade', models.IntegerField(default=0, verbose_name='Prioridade')),
                ('multi_pallet', models.BooleanField(default=False, verbose_name='Multi Pallet')),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado'), ('inativo', 'Inativo')], max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Endereço Estoque',
                'verbose_name_plural': 'Endereços Estoque',
                'constraints': [models.UniqueConstraint(fields=('nome', 'coluna', 'altura'), name='enderecos_unique_endereco', violation_error_message='Nome, Coluna e Altura são campos unicos')],
            },
        ),
        migrations.CreateModel(
            name='Pallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produtos', models.IntegerField(default=0, verbose_name='Quantidade de Produtos')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='estoque.enderecos', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Pallet',
                'verbose_name_plural': 'Pallets',
            },
        ),
        migrations.CreateModel(
            name='ProdutosPallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Quantidade')),
                ('lote_fornecedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote Fornecedor')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='estoque.pallets', verbose_name='Pallet')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.produtos', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto Pallet',
                'verbose_name_plural': 'Produtos Pallet',
            },
        ),
        migrations.AddConstraint(
            model_name='pallets',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_produtos__gte', 0)), name='pallets_check_quantidade_produtos', violation_error_message='Quantidade de Produtos precisa ser maior ou igual a 0'),
        ),
        migrations.AddConstraint(
            model_name='produtospallets',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 0)), name='produtospallets_check_quantidade', violation_error_message='Quantidade precisa ser maior ou igual a 0'),
        ),
    ]
