# Generated by Django 5.1 on 2025-12-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecos',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponivel'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado'), ('inativo', 'Inativo')], default='disponivel', max_length=20, verbose_name='Status'),
        ),
    ]
