# Generated by Django 5.1 on 2025-12-11 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_enderecos_status'),
        ('home', '0083_fornecedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtospallets',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.fornecedores', verbose_name='Fornecedor'),
        ),
    ]
