# Generated by Django 5.1 on 2025-12-11 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_produtospallets_fornecedor'),
        ('home', '0085_produtos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecos',
            name='tipo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.produtostipos', verbose_name='Tipo de Produto'),
        ),
    ]
