# Generated by Django 5.1 on 2025-12-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_enderecos_tipo_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enderecos',
            options={'ordering': ('nome', 'coluna', '-altura'), 'verbose_name': 'Endereço Estoque', 'verbose_name_plural': 'Endereços Estoque'},
        ),
    ]
