# Generated by Django 5.1 on 2025-12-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_enderecos_options'),
        ('home', '0085_produtos_tipo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='produtospallets',
            name='produtospallets_check_quantidade',
        ),
        migrations.AddConstraint(
            model_name='produtospallets',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='produtospallets_check_quantidade', violation_error_message='Quantidade precisa ser maior que 0'),
        ),
    ]
