# Generated by Django 5.1 on 2026-02-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_remove_produtospallets_produtospallets_check_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtospallets',
            name='aprovado',
            field=models.BooleanField(default=True, verbose_name='Aprovado'),
        ),
    ]
