# Generated by Django 5.1 on 2024-11-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cbo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero')),
                ('descricao', models.CharField(max_length=70, verbose_name='Descrição')),
                ('chave_migracao', models.IntegerField(blank=True, null=True, verbose_name='Chave Migração')),
            ],
            options={
                'verbose_name': 'CBO',
                'verbose_name_plural': 'CBO',
                'constraints': [models.UniqueConstraint(fields=('descricao',), name='cbo_unique_descricao', violation_error_message='Descrição é unico em CBO')],
            },
        ),
    ]
