# Generated by Django 5.1 on 2024-11-05 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_cidades_chave_migracao_and_more'),
        ('rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dissidios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('data', models.DateField(verbose_name='Data')),
                ('dissidio_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Dissidio Real %')),
                ('dissidio_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Dissidio Adicional %')),
                ('observacoes', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observações')),
                ('chave_migracao', models.IntegerField(blank=True, null=True, verbose_name='Chave Migração')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.jobs', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Dissidio',
                'verbose_name_plural': 'Dissidios',
                'constraints': [models.UniqueConstraint(fields=('job', 'data'), name='dissidios_unique_job_data', violation_error_message='Job e Data são unicos em Dissidios'), models.CheckConstraint(condition=models.Q(('dissidio_real__gte', 0)), name='dissidios_check_dissidio_real', violation_error_message='Dissidio Real precisa ser maior ou igual a 0'), models.CheckConstraint(condition=models.Q(('dissidio_adicional__gte', 0)), name='dissidios_check_dissidio_adicional', violation_error_message='Dissidio Adicional precisa ser maior ou igual a 0')],
            },
        ),
    ]
