# Generated by Django 5.1 on 2024-11-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_dissidios_aplicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaridades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=70, verbose_name='Descrição')),
                ('chave_migracao', models.IntegerField(blank=True, null=True, verbose_name='Chave Migração')),
            ],
            options={
                'verbose_name': 'Escolaridade',
                'verbose_name_plural': 'Escolaridades',
                'constraints': [models.UniqueConstraint(fields=('descricao',), name='escolaridades_unique_descricao', violation_error_message='Descrição é unico em Escolaridades')],
            },
        ),
    ]
