# Generated by Django 5.1 on 2024-11-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_transportelinhas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependentesTipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('chave_migracao', models.IntegerField(blank=True, null=True, verbose_name='Chave Migração')),
            ],
            options={
                'verbose_name': 'Dependentes Tipo',
                'verbose_name_plural': 'Dependentes Tipos',
                'constraints': [models.UniqueConstraint(fields=('descricao',), name='dependentestipos_unique_descricao', violation_error_message='Descrição é unico em Dependentes Tipos')],
            },
        ),
    ]
