# Generated by Django 5.1 on 2024-11-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_dependentestipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporteTipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('chave_migracao', models.IntegerField(blank=True, null=True, verbose_name='Chave Migração')),
            ],
            options={
                'verbose_name': 'Transporte Tipo',
                'verbose_name_plural': 'Transporte Tipos',
                'constraints': [models.UniqueConstraint(fields=('descricao',), name='transportetipos_unique_descricao', violation_error_message='Descrição é unico em Transporte Tipos')],
            },
        ),
    ]
