# Generated by Django 5.1 on 2024-11-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_transportetipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('plano_contas', models.CharField(choices=[('MK', 'MK - Adm., Logistica, Comercial, etc'), ('CP', 'CP - Produção, Manutenção, etc'), ('MK/CP', 'MK/CP - Compras, Limpeza, etc')], help_text='Pedir ajuda se tiver duvida em escolher, este campo interfere diretamente no custo dos produtos', max_length=5, verbose_name='Plano de Contas')),
                ('chave_migracao', models.IntegerField(blank=True, null=True, verbose_name='Chave Migração')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'constraints': [models.UniqueConstraint(fields=('descricao',), name='setores_unique_descricao', violation_error_message='Descrição é unico em Setores')],
            },
        ),
    ]
