# Generated by Django 5.1 on 2024-11-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_remove_funcoes_atualizado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField(verbose_name='Inicio')),
                ('intervalo_inicio', models.TimeField(verbose_name='Intervalo Inicio')),
                ('intervalo_fim', models.TimeField(verbose_name='Intervalo Fim')),
                ('fim', models.TimeField(verbose_name='Fim')),
                ('sexta_fim', models.TimeField(verbose_name='Sexta Fim')),
                ('chave_migracao', models.IntegerField(blank=True, null=True, verbose_name='Chave Migração')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'constraints': [models.UniqueConstraint(fields=('inicio', 'intervalo_inicio', 'intervalo_fim', 'fim', 'sexta_fim'), name='horarios_unique_horario', violation_error_message='Horario é unico em Horarios')],
            },
        ),
    ]
