# Generated by Django 5.1 on 2024-11-07 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_assistentestecnicosagenda_assistente_tecnico_and_more'),
        ('rh', '0011_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissidios',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.jobs', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='funcoes',
            name='cbo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.cbo', verbose_name='CBO'),
        ),
    ]
