# Generated by Django 5.1 on 2024-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0013_funcionarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='cnh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNH'),
        ),
    ]
