# Generated by Django 5.1 on 2024-11-08 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0014_alter_funcionarios_cnh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afastamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('data_afastamento', models.DateField(verbose_name='Data Afastamento')),
                ('data_previsao_retorno', models.DateField(blank=True, null=True, verbose_name='Data Previsão Reterno')),
                ('data_retorno', models.DateField(blank=True, null=True, verbose_name='Data Reterno')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo')),
                ('chave_migracao', models.IntegerField(blank=True, null=True, verbose_name='Chave Migração')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.funcionarios', verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Afastamento',
                'verbose_name_plural': 'Afastamentos',
                'constraints': [models.UniqueConstraint(fields=('funcionario', 'data_afastamento'), name='afastamentos_unique_afastamento', violation_error_message='Afastamento é unico em Afastamentos por Funcionario')],
            },
        ),
    ]
