# Generated by Django 5.1 on 2024-11-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0015_afastamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afastamentos',
            name='data_retorno',
            field=models.DateField(blank=True, null=True, verbose_name='Data Retorno'),
        ),
    ]
