# Generated by Django 5.1 on 2024-11-12 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0017_alter_afastamentos_data_previsao_retorno_dependentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorariosFuncionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('dias', models.CharField(choices=[('SEGUNDA A SABADO, DOMINGO LIVRE', 'Segunda a sabado, domingo livre'), ('SEGUNDA A SEXTA, SABADO E DOMINGO LIVRE', 'Srgunda a sexta, sabado e domingo livre'), ('SEGUNDA A SEXTA E SABADO ALTERNADO, DOMINGO LIVRE', 'Segunda a sexta e sabado alternado, domingo livre')], max_length=50, verbose_name='Dias')),
                ('data_inicio', models.DateField(verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.funcionarios', verbose_name='Funcionario')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.horarios', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Horario Funcionario',
                'verbose_name_plural': 'Horarios Funcionario',
            },
        ),
    ]
