# Generated by Django 5.1 on 2024-11-12 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0019_cipa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeTransportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitario R$')),
                ('quantidade_por_dia', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Quantidade por Dia')),
                ('dias', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Dias')),
                ('chave_migracao', models.IntegerField(blank=True, null=True, verbose_name='Chave Migração')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.transportelinhas', verbose_name='Linha')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.transportetipos', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Vale Transporte',
                'verbose_name_plural': 'Vale Transportes',
                'constraints': [models.UniqueConstraint(fields=('linha', 'tipo'), name='valetransportes_unique_valetransporte', violation_error_message='Linha e Tipo são unicos em Vale Transportes'), models.CheckConstraint(condition=models.Q(('valor_unitario__gt', 0)), name='valetransportes_check_valor_unitario', violation_error_message='Valor Unitario precisa ser maior que 0'), models.CheckConstraint(condition=models.Q(('quantidade_por_dia__gt', 0)), name='valetransportes_check_quantidade_por_dia', violation_error_message='Quantidade por Dia precisa ser maior que 0'), models.CheckConstraint(condition=models.Q(('dias__gt', 0)), name='valetransportes_check_dias', violation_error_message='Dias precisa ser maior que 0')],
            },
        ),
    ]
