# Generated by Django 5.1 on 2024-11-13 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0020_valetransportes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeTransportesFuncionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('quantidade_por_dia', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Quantidade por Dia')),
                ('dias', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Dias')),
                ('chave_migracao', models.IntegerField(blank=True, null=True, verbose_name='Chave Migração')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.funcionarios', verbose_name='Funcionario')),
                ('vale_transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.valetransportes', verbose_name='Vale Transporte')),
            ],
            options={
                'verbose_name': 'Vale Transporte Funcionario',
                'verbose_name_plural': 'Vale Transportes Funcionarios',
                'constraints': [models.UniqueConstraint(fields=('funcionario', 'vale_transporte'), name='valetransportesfuncionarios_unique_valetransporte', violation_error_message='Vale Transporte é unico em Vale Transportes de Funcionarios'), models.CheckConstraint(condition=models.Q(('quantidade_por_dia__gte', 0)), name='valetransportesfuncionarios_check_quantidade_por_dia', violation_error_message='Quantidade por Dia precisa ser maior ou igual a 0'), models.CheckConstraint(condition=models.Q(('dias__gte', 0)), name='valetransportesfuncionarios_check_dias', violation_error_message='Dias precisa ser maior ou igual a 0')],
            },
        ),
    ]
