# Generated by Django 5.1 on 2024-11-13 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0022_alter_valetransportes_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valetransportesfuncionarios',
            name='vale_transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vale_transportes_funcionarios', to='rh.valetransportes', verbose_name='Vale Transporte'),
        ),
    ]
