# Generated by Django 5.1 on 2024-11-13 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0023_alter_valetransportesfuncionarios_vale_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valetransportesfuncionarios',
            name='vale_transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.valetransportes', verbose_name='Vale Transporte'),
        ),
    ]
