# Generated by Django 5.1 on 2024-11-14 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0024_alter_valetransportesfuncionarios_vale_transporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('periodo_trabalhado_inicio', models.DateField(verbose_name='Periodo Trabalhado Inicio')),
                ('periodo_trabalhado_fim', models.DateField(verbose_name='Periodo Trabalhado Fim')),
                ('dias_ferias', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Dias de Ferias')),
                ('dias_desconsiderar', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Dias Desconsiderar')),
                ('dias_abono', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Dias Abono')),
                ('antecipar_abono', models.BooleanField(default=False, verbose_name='Antecipar Abono')),
                ('antecipar_13', models.BooleanField(default=False, verbose_name='Antecipar 1ª parcela 13º')),
                ('periodo_descanso_inicio', models.DateField(blank=True, null=True, verbose_name='Periodo Descanso Inicio')),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações')),
                ('chave_migracao', models.IntegerField(blank=True, null=True, verbose_name='Chave Migração')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.funcionarios', verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Ferias',
                'verbose_name_plural': 'Ferias',
                'constraints': [models.CheckConstraint(condition=models.Q(('dias_ferias__gt', 0)), name='ferias_check_dias_ferias', violation_error_message='Dias de Ferias precisa ser maior que 0'), models.CheckConstraint(condition=models.Q(('dias_desconsiderar__gte', 0)), name='ferias_check_dias_desconsiderar', violation_error_message='Dias Desconsiderar precisa ser maior ou igual a 0'), models.CheckConstraint(condition=models.Q(('dias_abono__gte', 0)), name='ferias_check_dias_abono', violation_error_message='Dias Abono precisa ser maior ou igual a 0')],
            },
        ),
    ]
