# Generated by Django 5.1 on 2024-11-14 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0025_ferias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('data', models.DateField(verbose_name='Data')),
                ('modalidade', models.CharField(choices=[('HORISTA', 'Horista'), ('MENSALISTA', 'Mensalista')], max_length=20, verbose_name='Modalidade')),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salario R$')),
                ('motivo', models.CharField(choices=[('ADMISSAO', 'Admissão'), ('DISSIDIO', 'Dissidio'), ('OUTROS', 'Outros'), ('PROMOCAO EXTRA FUNCAO', 'Promoção Extra Função'), ('PROMOCAO INTRA FUNCAO', 'Promoção Intra Função'), ('REALINHAMENTO COM O MERCADO', 'Realinhamento com o mercado'), ('AJUSTE DE FUNCAO', 'Ajuste de Função')], help_text='Promoção Intra Função: Usado somente para alteração na comissão. Promoção Extra Função: Usado para alteração de cargo. ', max_length=30, verbose_name='Motivo')),
                ('comissao_carteira', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Comissão Carteira %')),
                ('comissao_dupla', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Comissão Dupla %')),
                ('comissao_geral', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Comissão Geral %')),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações')),
                ('chave_migracao', models.IntegerField(blank=True, null=True, verbose_name='Chave Migração')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.funcoes', verbose_name='Função')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.funcionarios', verbose_name='Funcionario')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.setores', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Salario',
                'verbose_name_plural': 'Salarios',
                'constraints': [models.UniqueConstraint(fields=('funcionario', 'data'), name='salarios_unique_data', violation_error_message='Data é unico em Salarios de Funcionarios'), models.CheckConstraint(condition=models.Q(('salario__gt', 0)), name='salarios_check_salario', violation_error_message='Salario precisa ser maior que 0'), models.CheckConstraint(condition=models.Q(('comissao_carteira__gte', 0)), name='salarios_check_comissao_carteira', violation_error_message='Comissão Carteira precisa ser maior ou igual a 0'), models.CheckConstraint(condition=models.Q(('comissao_dupla__gte', 0)), name='salarios_check_comissao_dupla', violation_error_message='Comissão Dupla precisa ser maior ou igual a 0'), models.CheckConstraint(condition=models.Q(('comissao_geral__gte', 0)), name='salarios_check_comissao_geral', violation_error_message='Comissão Geral precisa ser maior ou igual a 0')],
            },
        ),
    ]
