# Generated by Django 5.1 on 2024-11-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0027_alter_dissidios_aplicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosfuncionarios',
            name='dias',
            field=models.CharField(choices=[('SEGUNDA A SABADO, DOMINGO LIVRE', 'Segunda a sabado, domingo livre'), ('SEGUNDA A SEXTA, SABADO E DOMINGO LIVRE', 'Segunda a sexta, sabado e domingo livre'), ('SEGUNDA A SEXTA E SABADO ALTERNADO, DOMINGO LIVRE', 'Segunda a sexta e sabado alternado, domingo livre')], max_length=50, verbose_name='Dias'),
        ),
    ]
