# Generated by Django 5.1 on 2024-11-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0028_alter_horariosfuncionarios_dias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setores',
            options={'ordering': ('descricao',), 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
