# Generated by Django 5.1 on 2025-02-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_vendedoresregioes'),
        ('rh', '0030_comissoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComissoesVendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='rh.comissoes', verbose_name='Comissão')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='home.vendedores', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Comissão Vendedor',
                'verbose_name_plural': 'Comissão Vendedores',
                'constraints': [models.UniqueConstraint(fields=('vendedor', 'comissao'), name='comissoes_vendedores_unique', violation_error_message='Comissão e Vendedor são unicos em Comissões Vendedores')],
            },
        ),
    ]
