# Generated by Django 5.1 on 2025-02-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0031_comissoesvendedores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comissoesvendedores',
            options={'verbose_name': 'Comissão Divisão', 'verbose_name_plural': 'Comissão Divisões'},
        ),
    ]
