# Generated by Django 5.1 on 2025-02-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0032_alter_comissoesvendedores_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissoes',
            name='valor_mercadorias_parcelas_nao_dividido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Mercadorias Parcelas Não Dividido R$'),
        ),
    ]
