# Generated by Django 5.1 on 2025-03-07 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_vendedoresestados'),
        ('rh', '0033_comissoes_valor_mercadorias_parcelas_nao_dividido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data Emissão')),
                ('nota_fiscal', models.IntegerField(default=0, verbose_name='Nota Fiscal')),
                ('parcelas', models.IntegerField(default=0, verbose_name='Parcelas')),
                ('cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cliente')),
                ('inclusao_orcamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inclusão Orçamento')),
                ('especie', models.CharField(blank=True, choices=[('SAIDA', 'Saida'), ('ENTRADA', 'Entrada')], max_length=10, null=True, verbose_name='Especie')),
                ('status', models.CharField(blank=True, choices=[('CANCELADA', 'Cancelada')], max_length=10, null=True, verbose_name='Status')),
                ('valor_mercadorias', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Mercadorias R$')),
                ('valor_mercadorias_nao_dividido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Mercadorias Não Dividido R$')),
                ('divisao', models.BooleanField(default=False, verbose_name='Divisão')),
                ('erro', models.BooleanField(default=False, verbose_name='Erro')),
                ('infra', models.BooleanField(default=False, verbose_name='Infra')),
                ('premoldado_poste', models.BooleanField(default=False, verbose_name='Pre-Moldado / Poste')),
                ('carteira_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_carteira_cliente', to='home.vendedores', verbose_name='Carteira Cliente')),
                ('representante_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_representante_cliente', to='home.vendedores', verbose_name='Representante Cliente')),
                ('representante_nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_representante_nota', to='home.vendedores', verbose_name='Representante Nota')),
                ('segundo_representante_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_segundo_representante_cliente', to='home.vendedores', verbose_name='Segundo Representante Cliente')),
                ('segundo_representante_nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_segundo_representante_nota', to='home.vendedores', verbose_name='Segundo Representante Nota')),
                ('uf_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_uf_cliente', to='home.estados', verbose_name='UF Cliente')),
                ('uf_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_uf_entrega', to='home.estados', verbose_name='UF Entrega')),
            ],
            options={
                'verbose_name': 'Faturamento',
                'verbose_name_plural': 'Faturamentos',
            },
        ),
        migrations.CreateModel(
            name='FaturamentosVendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='rh.faturamentos', verbose_name='Faturamento')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='home.vendedores', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Faturamento Divisão',
                'verbose_name_plural': 'Faturamento Divisões',
                'constraints': [models.UniqueConstraint(fields=('vendedor', 'faturamento'), name='faturamento_vendedores_unique', violation_error_message='Faturamento e Vendedor são unicos em Faturamentos Vendedores')],
            },
        ),
    ]
