# Generated by Django 5.1 on 2025-03-20 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0034_faturamentos_faturamentosvendedores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremioAssiduidadeBasesCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano Referencia')),
                ('mes_referencia', models.IntegerField(choices=[(1, '01 - Janeiro'), (2, '02 - Fevereiro'), (3, '03 - Março'), (4, '04 - Abril'), (5, '05 - Maio'), (6, '06 - Junho'), (7, '07 - Julho'), (8, '08 - Agosto'), (9, '09 - Setembro'), (10, '10 - Outubro'), (11, '11 - Novembro'), (12, '12 - Dezembro')], verbose_name='Mes Referencia')),
                ('margem_contribuicao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Margem de Contribuição R$')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Premio Assiduidade Bases de Calculo',
                'verbose_name_plural': 'Premio Assiduidade Base de Calculo',
                'constraints': [models.UniqueConstraint(fields=('ano_referencia', 'mes_referencia'), name='premioassiduidadebasescalculo_unique', violation_error_message='Ano e Mes de referencia são unicos em Premio Assiduidade Bases Calculo')],
            },
        ),
    ]
