# Generated by Django 5.1 on 2025-05-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0035_premioassiduidadebasescalculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissoes',
            name='parede_concreto',
            field=models.BooleanField(default=False, verbose_name='Parede de Concreto'),
        ),
    ]
