# Generated by Django 5.1 on 2025-05-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0036_comissoes_parede_concreto'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamentos',
            name='parede_concreto',
            field=models.BooleanField(default=False, verbose_name='Parede Concreto'),
        ),
    ]
