# Generated by Django 5.1 on 2025-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0037_faturamentos_parede_concreto'),
    ]

    operations = [
        migrations.AddField(
            model_name='afastamentos',
            name='observacoes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações'),
        ),
    ]
