# Generated by Django 5.1 on 2025-08-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0038_afastamentos_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarios',
            name='motivo',
            field=models.CharField(choices=[('ADMISSAO', 'Admissão'), ('AJUSTE DE FUNCAO', 'Ajuste de Função'), ('AUMENTO ESPONTANEO', 'Aumento Espontâneo'), ('DISSIDIO', 'Dissidio'), ('OUTROS', 'Outros'), ('PROMOCAO EXTRA FUNCAO', 'Promoção Extra Função'), ('PROMOCAO INTRA FUNCAO', 'Promoção Intra Função'), ('REALINHAMENTO COM O MERCADO', 'Realinhamento com o mercado')], help_text='Promoção Intra Função: Usado somente para alteração na comissão. Promoção Extra Função: Usado para alteração de cargo. ', max_length=30, verbose_name='Motivo'),
        ),
    ]
