# Generated by Django 5.1 on 2026-06-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0039_alter_salarios_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferias',
            name='observacoes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Observações'),
        ),
    ]
