# Generated by Django 5.1 on 2025-01-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadoras',
            name='chave_migracao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chave Migração'),
        ),
    ]
