# Generated by Django 5.1 on 2025-01-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frete', '0003_transportadorasorigemdestino'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadorasorigemdestino',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='Status'),
        ),
    ]
