# Generated by Django 5.1 on 2025-01-15 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frete', '0004_transportadorasorigemdestino_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportadorasRegioesValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('atendimento_cidades_especificas', models.BooleanField(default=True, help_text='Desmarcar para considerar todas as cidades do estado de destino, desconsiderando as cidades especificadas em outras regiões da mesma transportadora', verbose_name='Atendimento Cidades Especificas')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='Status')),
                ('razao', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Razão (kg/m³)')),
                ('advaloren', models.DecimalField(decimal_places=2, default=0, help_text='Porcentagem sobre o valor das mercadorias', max_digits=9, verbose_name='Advaloren / Frete Valor (%)')),
                ('advaloren_valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Valor Minimo Advaloren / Frete Valor (R$)')),
                ('gris', models.DecimalField(decimal_places=2, default=0, help_text='Porcentagem sobre o valor das mercadorias', max_digits=9, verbose_name='Gris / Gerenciamento de Risco (%)')),
                ('gris_valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Valor Minimo Gris / Gerenciamento de Risco (R$)')),
                ('taxa_coleta', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Taxa de Coleta (R$)')),
                ('taxa_conhecimento', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Taxa de Conhecimento (R$)')),
                ('taxa_sefaz', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Taxa Sefaz / TAS (R$)')),
                ('taxa_suframa', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Taxa Suframa (R$)')),
                ('pedagio_fracao', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Pedagio Fração (kg)')),
                ('pedagio_valor_fracao', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Pedagio Valor da Fração (R$)')),
                ('pedagio_valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Pedagio Valor Minimo (R$)')),
                ('valor_kg', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Valor/kg (R$)')),
                ('valor_kg_excedente', models.BooleanField(default=False, help_text='Marcar para considerar somente os kgs a mais do maior kg definido nas margens de kg', verbose_name='Valor/kg Excedente')),
                ('taxa_frete_peso', models.DecimalField(decimal_places=2, default=0, help_text='Frete peso é o resultado final de acordo com os valores nas margens de kg e valor/kg', max_digits=9, verbose_name='Outras Taxas sobre frete peso (%)')),
                ('taxa_frete_peso_valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Valor Minimo Outras Taxas sobre frete peso (R$)')),
                ('taxa_valor_mercadorias', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Outras Taxas sobre valor das mercadorias (%)')),
                ('taxa_valor_mercadorias_valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Valor Minimo Outras Taxas sobre valor das mercadorias (R$)')),
                ('frete_minimo_valor', models.DecimalField(decimal_places=2, default=0, help_text='Valor a ser considerado quando a soma de todo custo de frete (liquido de ICMS) for menor que o informado', max_digits=9, verbose_name='Frete Minimo (R$)')),
                ('frete_minimo_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Valor a ser considerado quando a soma de todo custo de frete (liquido de ICMS) for menor que o informado', max_digits=9, verbose_name='Frete Minimo sobre valor das mercadorias (%)')),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações')),
                ('prazo_tipo', models.CharField(blank=True, choices=[('DIAS', 'Dias'), ('DIAS UTEIS', 'Dias Uteis')], max_length=10, null=True, verbose_name='Prazo Tipo')),
                ('prazo_padrao', models.IntegerField(default=0, verbose_name='Prazo Padrão')),
                ('frequencia_padrao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Frequencia Padrão')),
                ('observacoes_prazo_padrao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações Prazo Padrão')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('transportadora_origem_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='frete.transportadorasorigemdestino', verbose_name='Transportadora / Origem - Destino')),
            ],
            options={
                'verbose_name': 'Transportadoras Região Valores',
                'verbose_name_plural': 'Transportadoras Regiões Valores',
                'constraints': [models.UniqueConstraint(fields=('transportadora_origem_destino', 'descricao'), name='transportadorasresgioesvalores_unique_regiao', violation_error_message='Origem, Destino e descrição são campos unicos')],
            },
        ),
    ]
