# Generated by Django 5.1 on 2025-01-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frete', '0005_transportadorasregioesvalores'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadorasregioesvalores',
            name='atendimento_zona_rural',
            field=models.BooleanField(default=True, verbose_name='Atendimento Zona Rural'),
        ),
        migrations.AddField(
            model_name='transportadorasregioesvalores',
            name='taxa_zona_rural',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor só é somado quando for selecionado zona rural no calculo do frete', max_digits=9, verbose_name='Taxa Zona Rural (R$)'),
        ),
    ]
