# Generated by Django 5.1 on 2025-01-17 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frete', '0006_transportadorasregioesvalores_atendimento_zona_rural_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportadorasRegioesMargens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('ate_kg', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Até kg')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Valor (R$)')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('transportadora_regiao_valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='frete.transportadorasregioesvalores', verbose_name='Transportadora Região')),
            ],
            options={
                'verbose_name': 'Transportadoras Região Margem',
                'verbose_name_plural': 'Transportadoras Região Margens',
                'constraints': [models.UniqueConstraint(fields=('transportadora_regiao_valor', 'ate_kg'), name='transportadorasresgioesmargens_unique_kg', violation_error_message='Transportadora Região e Até kg são campos unicos'), models.CheckConstraint(condition=models.Q(('ate_kg__gt', 0)), name='transportadorasresgioesmargens_check_ate_kg', violation_error_message='Até kg precisa ser maior que 0'), models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='transportadorasresgioesmargens_check_valor', violation_error_message='Valor precisa ser maior que 0')],
            },
        ),
    ]
