# Generated by Django 5.1 on 2025-01-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frete', '0008_transportadorasregioescidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportadorasregioescidades',
            name='transportadora_regiao_valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='frete.transportadorasregioesvalores', verbose_name='Transportadora Região Valor'),
        ),
    ]
