# Generated by Django 5.1 on 2025-01-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frete', '0009_alter_transportadorasregioescidades_transportadora_regiao_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportadorasregioesvalores',
            old_name='taxa_valor_mercadorias',
            new_name='taxa_valor_nota',
        ),
        migrations.RenameField(
            model_name='transportadorasregioesvalores',
            old_name='taxa_valor_mercadorias_valor_minimo',
            new_name='taxa_valor_nota_valor_minimo',
        ),
        migrations.AlterField(
            model_name='transportadorasregioesvalores',
            name='advaloren',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentagem sobre o valor da nota',
                                      max_digits=9, verbose_name='Advaloren / Frete Valor (%)'),
        ),
        migrations.AlterField(
            model_name='transportadorasregioesvalores',
            name='frete_minimo_percentual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor a ser considerado quando a soma de todo custo de frete (liquido de ICMS) for menor que o informado',
                                      max_digits=9, verbose_name='Frete Minimo sobre valor da nota (%)'),
        ),
        migrations.AlterField(
            model_name='transportadorasregioesvalores',
            name='gris',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentagem sobre o valor da nota',
                                      max_digits=9, verbose_name='Gris / Gerenciamento de Risco (%)'),
        ),
    ]
