# Generated by Django 5.1 on 2025-01-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frete', '0011_alter_transportadorasregioesvalores_taxa_valor_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportadorasregioesvalores',
            name='taxa_valor_nota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Outras Taxas sobre valor da nota (%)'),
        ),
        migrations.AlterField(
            model_name='transportadorasregioesvalores',
            name='taxa_valor_nota_valor_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Valor Minimo Outras Taxas sobre valor da nota (R$)'),
        ),
    ]
