# Generated by Django 5.1 on 2025-02-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frete', '0013_alter_transportadorasregioesvalores_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportadoras',
            options={'ordering': ('nome',), 'verbose_name': 'Transportadora', 'verbose_name_plural': 'Transportadoras'},
        ),
        migrations.AlterModelOptions(
            name='transportadorasregioesmargens',
            options={'ordering': ('ate_kg',), 'verbose_name': 'Transportadoras Região Margem', 'verbose_name_plural': 'Transportadoras Região Margens'},
        ),
    ]
