# Generated by Django 5.1 on 2025-02-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frete', '0014_alter_transportadoras_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadorasregioesvalores',
            name='arquivo_migrar_cidades',
            field=models.FileField(blank=True, default='', help_text='A migração será feita ao salvar e excluirá o arquivo automaticamente', null=True, upload_to='frete/migrar_cidades/%Y/%m/', verbose_name='Arquivo Migrar Cidades e Prazos'),
        ),
    ]
