# Generated by Django 5.1 on 2025-02-11 12:04

import frete.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frete', '0015_transportadorasregioesvalores_arquivo_migrar_cidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportadorasregioesvalores',
            name='arquivo_migrar_cidades',
            field=models.FileField(blank=True, default='', help_text=frete.models.get_help_text_migrar_cidades, null=True, upload_to='frete/migrar_cidades/%Y/%m/', verbose_name='Arquivo Migrar Cidades e Prazos'),
        ),
    ]
