# Generated by Django 5.1 on 2026-07-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frete', '0017_alter_transportadorasregioesmargens_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportadorasregioesvalores',
            name='taxa_dificuldade_entrega',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nos CNPJs definidos', max_digits=9, verbose_name='Taxa Dificildade Entrega / TDE (R$)'),
        ),
    ]
