# Generated by Django 5.1 on 2026-07-07 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frete', '0018_transportadorasregioesvalores_taxa_dificuldade_entrega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportadorasregioesvalores',
            name='taxa_dificuldade_entrega',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nos CNPJs definidos', max_digits=9, verbose_name='Taxa Dificuldade Entrega / TDE (R$)'),
        ),
        migrations.CreateModel(
            name='TransportadorasTaxasCnpj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ / Raiz CNPJ')),
                ('taxa_dificuldade_entrega', models.DecimalField(decimal_places=2, default=0, help_text='Deixar 0 para usar o definido em valores', max_digits=9, verbose_name='Taxa Dificuldade Entrega / TDE (R$)')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='frete.transportadoras', verbose_name='Transportadora')),
            ],
            options={
                'verbose_name': 'Transportadoras Taxas por CNPJ',
                'verbose_name_plural': 'Transportadoras Taxas por CNPJ',
                'constraints': [models.UniqueConstraint(fields=('transportadora', 'cnpj'), name='transportadorastaxascnpj_unique_cnpj', violation_error_message='Transportadora e CNPJ são campos unicos')],
            },
        ),
    ]
