# Generated by Django 5.1 on 2025-09-26 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsRdStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('chave_analysis', models.IntegerField(blank=True, null=True, verbose_name='ID Analysis')),
                ('dados_bruto', models.TextField(blank=True, null=True, verbose_name='Dados Bruto')),
                ('identificador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identificador')),
                ('criado_em', models.DateTimeField(blank=True, null=True, verbose_name='Criado Em')),
                ('conversion_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='URL de Conversão')),
                ('conversion_domain', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dominio de Conversão')),
                ('email_lead', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('user_agent', models.CharField(blank=True, max_length=1000, null=True, verbose_name='User Agent')),
                ('device', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dispositivo')),
                ('asset_id', models.IntegerField(blank=True, null=True, verbose_name='ID Asset')),
                ('conversion_payload', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Payload de Conversão')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
                ('origem', models.CharField(blank=True, max_length=100, null=True, verbose_name='Origem')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Lead RD Station',
                'verbose_name_plural': 'Leads RD Station',
            },
        ),
    ]
