# Generated by Django 5.1 on 2025-09-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsrdstation',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='leadsrdstation',
            name='atualizado_por',
        ),
        migrations.RemoveField(
            model_name='leadsrdstation',
            name='criado_por',
        ),
    ]
