# Generated by Django 5.1 on 2025-09-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_remove_leadsrdstation_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsrdstation',
            name='lead_valido',
            field=models.BooleanField(default=True, verbose_name='Lead Valido'),
        ),
        migrations.AddField(
            model_name='leadsrdstation',
            name='observacoes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações'),
        ),
    ]
