# Generated by Django 5.1 on 2025-10-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_leadsrdstation_lead_valido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsrdstation',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado Em'),
        ),
    ]
