# Generated by Django 5.1 on 2025-10-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_leadsrdstation_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsrdstation',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Criado Em'),
        ),
    ]
