# Generated by Django 5.1 on 2025-10-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_alter_leadsrdstation_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsrdstation',
            name='interesse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Interesse'),
        ),
        migrations.AddField(
            model_name='leadsrdstation',
            name='mensagem',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem'),
        ),
    ]
