# Generated by Django 5.1 on 2025-10-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_leadsrdstation_interesse_leadsrdstation_mensagem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='leadsrdstation',
            constraint=models.UniqueConstraint(fields=('empresa',), name='leadsrdstation_unique_empresa', violation_error_message='Empresa é unico em Leads RD Station'),
        ),
    ]
