# Generated by Django 5.1 on 2025-10-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_leadsrdstation_leadsrdstation_unique_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsrdstation',
            name='chave_analysis',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Cliente Analysis'),
        ),
        migrations.AddConstraint(
            model_name='leadsrdstation',
            constraint=models.UniqueConstraint(fields=('chave_analysis',), name='leadsrdstation_unique_chave_analysis', violation_error_message='ID Cliente Analysis é unico em Leads RD Station'),
        ),
    ]
