# Generated by Django 5.1 on 2025-10-06 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_alter_leadsrdstation_chave_analysis_and_more'),
        ('rh', '0039_alter_salarios_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsrdstation',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.funcionarios', verbose_name='Responsavel'),
        ),
    ]
