# Generated by Django 5.1 on 2025-10-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_leadsrdstation_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsrdstation',
            name='responsavel',
        ),
    ]
