# Generated by Django 5.1 on 2025-10-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_responsaveis'),
        ('marketing', '0010_remove_leadsrdstation_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsrdstation',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.responsaveis', verbose_name='Responsavel'),
        ),
    ]
