# Generated by Django 5.1 on 2026-03-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_alter_produtos_tipo'),
        ('marketing', '0011_leadsrdstation_responsavel'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leadsrdstation',
            name='leadsrdstation_unique_empresa',
        ),
        migrations.RemoveConstraint(
            model_name='leadsrdstation',
            name='leadsrdstation_unique_chave_analysis',
        ),
        migrations.AddConstraint(
            model_name='leadsrdstation',
            constraint=models.UniqueConstraint(fields=('empresa', 'criado_em'), name='leadsrdstation_unique_empresa', violation_error_message='Empresa e Data de Criação são unicos em Leads RD Station'),
        ),
        migrations.AddConstraint(
            model_name='leadsrdstation',
            constraint=models.UniqueConstraint(fields=('chave_analysis', 'criado_em'), name='leadsrdstation_unique_chave_analysis', violation_error_message='ID Cliente Analysis e Data de Criação são unicos em Leads RD Station'),
        ),
    ]
