# Generated by Django 5.1 on 2026-04-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_remove_leadsrdstation_leadsrdstation_unique_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsrdstation',
            name='recadastro',
            field=models.BooleanField(default=False, verbose_name='Recadastro'),
        ),
    ]
