# Generated by Django 5.1 on 2024-11-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_relatorios', '0003_aniversariantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aniversariantes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job', models.CharField(blank=True, max_length=30, null=True, verbose_name='Job')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('mes_nascimento', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='Mes Nascimento')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
            ],
            options={
                'verbose_name': 'Relatorio Aniversariante',
                'verbose_name_plural': 'Relatorio Aniversariantes',
                'db_table': 'rh_aniversariantes_view',
                'managed': False,
            },
        ),
    ]
