# Generated by Django 5.1 on 2024-11-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_relatorios', '0005_dependentes_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependentes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job', models.CharField(blank=True, max_length=30, null=True, verbose_name='Job')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('sexo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sexo')),
                ('nome_dependente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Dependente')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('idade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Idade')),
                ('crianca', models.BooleanField(blank=True, null=True, verbose_name='Criança')),
            ],
            options={
                'verbose_name': 'Relatorio Dependente',
                'verbose_name_plural': 'Relatorio Dependentes',
                'db_table': 'rh_dependentes_view',
                'managed': False,
            },
        ),
    ]
