# Generated by Django 5.1 on 2024-11-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_relatorios', '0005_filhos_12_anos_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filhos12Anos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job', models.CharField(blank=True, max_length=30, null=True, verbose_name='Job')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('nome_dependente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Dependente')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('idade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Idade')),
            ],
            options={
                'verbose_name': 'Relatorio Filhos até 12 Anos',
                'verbose_name_plural': 'Relatorio Filhos até 12 Anos',
                'db_table': 'rh_filhos_12_anos_view',
                'managed': False,
            },
        ),
    ]
