# Generated by Django 5.1 on 2024-11-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_relatorios', '0008_listagem_funcionarios_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionariosListagem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job', models.CharField(blank=True, max_length=30, null=True, verbose_name='Job')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('funcao', models.CharField(blank=True, max_length=70, null=True, verbose_name='Função')),
                ('sexo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('membro_cipa', models.BooleanField(blank=True, null=True, verbose_name='Membro CIPA')),
            ],
            options={
                'verbose_name': 'Listagem Funcionario',
                'verbose_name_plural': 'Listagem Funcionarios',
                'db_table': 'rh_listagem_funcionarios_view',
                'managed': False,
            },
        ),
    ]
