# Generated by Django 5.1 on 2024-11-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_relatorios', '0016_quadro_horarios_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionariosQuadroHorarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job', models.CharField(blank=True, max_length=30, null=True, verbose_name='Job')),
                ('registro', models.IntegerField(blank=True, null=True, verbose_name='Registro')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('carteira_profissional', models.CharField(blank=True, max_length=10, null=True, verbose_name='Carteira Profissional')),
                ('setor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Setor')),
                ('funcao', models.CharField(blank=True, max_length=70, null=True, verbose_name='Função')),
                ('horario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Horario')),
                ('almoco', models.CharField(blank=True, max_length=20, null=True, verbose_name='Almoço')),
            ],
            options={
                'verbose_name': 'Funcionario Quadro de Horario',
                'verbose_name_plural': 'Funcionarios Quadro de Horarios',
                'db_table': 'rh_quadro_horarios_view',
                'managed': False,
            },
        ),
    ]
