# Generated by Django 5.1 on 2024-11-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh_relatorios', '0017_funcionariosquadrohorarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionarioshistoricosalarios',
            options={'managed': False, 'verbose_name': 'Relatorio Historico de Salarios de Funcionarios', 'verbose_name_plural': 'Relatorio Historico de Salarios de Funcionarios'},
        ),
        migrations.AlterModelOptions(
            name='funcionariosquadrohorarios',
            options={'managed': False, 'verbose_name': 'Quadro de Horarios de Funcionarios', 'verbose_name_plural': 'Quadro de Horarios de Funcionarios'},
        ),
        migrations.AlterModelOptions(
            name='funcionariossalariofuncaoatual',
            options={'managed': False, 'verbose_name': 'Relatorio Salario Função Atual de Funcionarios', 'verbose_name_plural': 'Relatorio Salario Função Atual de Funcionarios'},
        ),
    ]
