# Generated by Django 5.1 on 2025-11-28 18:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0082_responsaveis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivosRnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Motivo RNC',
                'verbose_name_plural': 'Motivos RNC',
                'ordering': ('descricao',),
                'constraints': [models.UniqueConstraint(fields=('descricao',), name='motivos_rnc_unique_descricao', violation_error_message='Descrição é campo unico')],
            },
        ),
        migrations.CreateModel(
            name='RncNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('nota_fiscal', models.IntegerField(verbose_name='Nº Nota Fiscal')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('acao_imediata', models.TextField(verbose_name='Ação Imediata')),
                ('origem', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo')], max_length=20, verbose_name='Origem')),
                ('follow_up', models.TextField(blank=True, null=True, verbose_name='Follow-Up')),
                ('custo_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Custo Adicional R$')),
                ('custo_recuperado', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Custo Recuperado R$')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.jobs', verbose_name='Job')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='vendas.motivosrnc', verbose_name='Motivo')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.responsaveis', verbose_name='Responsavel')),
            ],
            options={
                'verbose_name': 'RNC Nota',
                'verbose_name_plural': 'RNC Notas',
                'constraints': [models.UniqueConstraint(fields=('job', 'nota_fiscal'), name='rnc_notas_unique_nota', violation_error_message='Job e Nota Fiscal são campos unicos')],
            },
        ),
    ]
