# Generated by Django 5.1 on 2025-12-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rncnotas',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='rncnotas',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
