# Generated by Django 5.1 on 2025-12-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_remove_rncnotas_observacoes_rncnotas_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rncnotas',
            name='descricao',
            field=models.TextField(default=1, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
