# Generated by Django 5.1 on 2026-01-07 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_rncnotas_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rncnotas',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='vendas.motivosrnc', verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='rncnotas',
            name='origem',
            field=models.CharField(blank=True, choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo')], max_length=20, null=True, verbose_name='Origem'),
        ),
    ]
