# Generated by Django 5.1 on 2026-01-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_rncnotas_motivo_alter_rncnotas_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rncnotas',
            name='procedente',
            field=models.BooleanField(default=False, verbose_name='Procedente'),
        ),
    ]
