# Generated by Django 5.1 on 2024-08-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, unique=True, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, default='', max_length=255, unique=True, verbose_name='Slug')),
                ('tamanho_botao', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Medio'), ('grande', 'Grande')], default='grande', max_length=10, verbose_name='Tamanho do Botão')),
                ('imagem_capa', models.ImageField(blank=True, default='', upload_to='home/link_capa/', verbose_name='Imagem de Capa')),
                ('link_externo', models.BooleanField(default=False, verbose_name='Link Externo')),
                ('url_externo', models.CharField(max_length=2048, verbose_name='URL do Link Externo')),
                ('visivel', models.BooleanField(default=True, verbose_name='Visível')),
                ('conteudo', models.TextField(verbose_name='Conteudo')),
            ],
            options={
                'verbose_name': 'Home Link',
                'verbose_name_plural': 'Home Links',
            },
        ),
    ]
