# Generated by Django 5.1 on 2024-08-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelinks',
            name='url_externo',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='URL do Link Externo'),
        ),
    ]
