# Generated by Django 5.1 on 2024-08-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homelinks_url_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelinks',
            name='ordem',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=7, verbose_name='Ordem'),
        ),
    ]
