# Generated by Django 5.1 on 2024-08-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homelinks_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelinks',
            name='imagem_capa',
            field=models.ImageField(blank=True, default='', help_text='A imagem será redimensionada automaticamente ao incluir nova imagem de acordo com o tamanho do botão selecionado: Pequeno 74x74 px, Medio 220x74 px, Grande 220x168 px', upload_to='home/link_capa/', verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='homelinks',
            name='ordem',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Mudar numero para forçar outra ordenação', max_digits=7, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='homelinks',
            name='tamanho_botao',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Medio'), ('grande', 'Grande'), ('comunicado', 'Comunicado')], default='grande', help_text='Se alterar esse campo, inclua a imagem novamente para redimensionar', max_length=10, verbose_name='Tamanho do Botão'),
        ),
    ]
