# Generated by Django 5.1 on 2024-08-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homelinks_imagem_capa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelinks',
            name='imagem_capa',
            field=models.ImageField(blank=True, default='', help_text="Tamanho 'Consultoria de Vendas' não exibe imagem de capa, deixar em branco. A imagem será redimensionada automaticamente ao incluir nova imagem de acordo com o tamanho do botão selecionado: Pequeno 74x74 px, Medio 220x74 px, Grande 220x168 px", upload_to='home/link_capa/', verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='homelinks',
            name='tamanho_botao',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Medio'), ('grande', 'Grande'), ('comunicado', 'Comunicado'), ('consultoria', 'Consultoria de Vendas')], default='grande', help_text='Se alterar esse campo, inclua a imagem novamente para redimensionar', max_length=30, verbose_name='Tamanho do Botão'),
        ),
    ]
