# Generated by Django 5.1 on 2024-08-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homelinks_imagem_capa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelinks',
            name='conteudo',
            field=models.TextField(blank=True, null=True, verbose_name='Conteudo'),
        ),
    ]
