# Generated by Django 5.1 on 2024-10-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_sitesetup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetup',
            options={'verbose_name': 'Site Setup', 'verbose_name_plural': 'Site Setup'},
        ),
    ]
