# Generated by Django 5.1 on 2024-10-09 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_sitesetup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelinks',
            name='imagem_capa',
            field=models.ImageField(blank=True, default='', help_text="Tamanho 'Consultoria de Vendas' e 'Comunicado' não exibe imagem de capa, deixar em branco. A imagem será redimensionada automaticamente ao incluir nova imagem de acordo com o tamanho do botão selecionado: Pequeno 74x74 px, Medio 220x74 px, Grande 220x168 px", upload_to='home/link_capa/', verbose_name='Imagem de Capa'),
        ),
        migrations.CreateModel(
            name='HomeLinksDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Documento')),
                ('documento', models.FileField(upload_to='home/link_documento/', verbose_name='Documento')),
                ('home_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.homelinks', verbose_name='Home Link')),
            ],
            options={
                'verbose_name': 'Documento Home Link',
                'verbose_name_plural': 'Documentos Home Link',
            },
        ),
    ]
