# Generated by Django 5.1 on 2024-10-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homelinks_imagem_capa_homelinksdocumentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homelinksdocumentos',
            options={'ordering': ('nome',), 'verbose_name': 'Documento Home Link', 'verbose_name_plural': 'Documentos Home Link'},
        ),
        migrations.AlterField(
            model_name='homelinks',
            name='imagem_capa',
            field=models.ImageField(blank=True, default='', help_text="Tamanho 'Consultoria de Vendas' e 'Comunicado' não exibe imagem de capa, deixar em branco. A imagem será redimensionada automaticamente ao incluir nova imagem de acordo com o tamanho do botão selecionado: Pequeno 74x74 px, Medio 220x74 px, Grande 220x168 px", upload_to='home/link_capa/%Y/%m/', verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='homelinksdocumentos',
            name='documento',
            field=models.FileField(upload_to='home/link_documento/%Y/%m/', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='file',
            field=models.FileField(upload_to='home/link_conteudo/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, help_text='A imagem será redimensionada para 32x32 px', null=True, upload_to='home/favicon/%Y/%m/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='logo_cabecalho',
            field=models.ImageField(blank=True, help_text='A imagem será redimensionada proporcionalmente para 100 px de altura', null=True, upload_to='home/logo/%Y/%m/', verbose_name='Logo'),
        ),
    ]
