# Generated by Django 5.1 on 2024-10-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homelinks_homelinks_unique_titulo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='homelinks',
            constraint=models.CheckConstraint(condition=models.Q(('link_externo', True)), name='homelinks_check_url_externo', violation_error_message='Informar URL do Link Externo'),
        ),
    ]
