# Generated by Django 5.1 on 2024-10-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_homelinks_homelinks_check_url_externo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelinks',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='homelinks',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='Título'),
        ),
    ]
