# Generated by Django 5.1 on 2024-10-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_homelinks_homelinks_unique_titulo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='homelinksdocumentos',
            constraint=models.UniqueConstraint(fields=('nome', 'home_link'), name='homelinksdocumentos_unique_nome', violation_error_message='Nome é campo unico dentro de um Home Link'),
        ),
    ]
