# Generated by Django 5.1 on 2024-10-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_homelinksdocumentos_homelinksdocumentos_unique_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='despesa_administrativa_fixa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Despesa Administrativa Fixa %'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='dias_uteis_mes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Dias Uteis no Mês'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='meta_diaria',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Meta Diaria'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='meta_mes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Meta do Mês'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='primeiro_dia_mes',
            field=models.DateField(default='2000-01-01', verbose_name='Primeiro Dia do Mês'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='primeiro_dia_util_mes',
            field=models.DateField(default='2000-01-01', verbose_name='Primeiro Dia Util do Mês'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='primeiro_dia_util_proximo_mes',
            field=models.DateField(default='2000-01-01', verbose_name='Primeiro Dia Util do Proximo Mês'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='rentabilidade_amarela',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Rentabilidade Amarela %'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='rentabilidade_verde',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Rentabilidade Verde %'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='rentabilidade_vermelha',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Rentabilidade Vermelha %'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='ultimo_dia_mes',
            field=models.DateField(default='2000-01-01', verbose_name='Ultimo Dia do Mês'),
        ),
    ]
