# Generated by Django 5.1 on 2024-10-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_sitesetup_despesa_administrativa_fixa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='dias_uteis_mes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Dias Uteis no Mês'),
        ),
    ]
