# Generated by Django 5.1 on 2024-10-25 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_assistentestecnicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistentesTecnicosAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('agenda', models.CharField(max_length=50, verbose_name='Agenda')),
                ('assistente_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.assistentestecnicos', verbose_name='Assistente Tecnico')),
            ],
            options={
                'verbose_name': 'Agenda VEC',
                'verbose_name_plural': 'Agenda VEC',
                'ordering': ('-data',),
                'constraints': [models.UniqueConstraint(fields=('data', 'assistente_tecnico'), name='agenda_unique_data_assistente', violation_error_message='Assistente Tecnico e Data são unicos dentro da agenda')],
            },
        ),
    ]
