# Generated by Django 5.1 on 2024-10-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_assistentestecnicosagenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
                ('chave_migracao', models.IntegerField(null=True, verbose_name='Chave Migração')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=30, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'constraints': [models.UniqueConstraint(fields=('descricao',), name='jobs_unique_descricao', violation_error_message='Descrição é unica em Jobs')],
            },
        ),
    ]
