# Generated by Django 5.1 on 2024-10-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_paises'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paises',
            constraint=models.UniqueConstraint(fields=('chave_analysis',), name='paises_unique_chave_analysis', violation_error_message='Chave Analysis é unico em Países'),
        ),
    ]
