# Generated by Django 5.1 on 2024-10-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_paises_paises_unique_chave_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paises',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_analysis', models.IntegerField(verbose_name='ID Analysis')),
                ('uf', models.CharField(max_length=30, verbose_name='UF')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla')),
                ('chave_migracao', models.IntegerField(null=True, verbose_name='Chave Migração')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'constraints': [models.UniqueConstraint(fields=('uf',), name='estados_unique_uf', violation_error_message='UF é unico em Estados'), models.UniqueConstraint(fields=('chave_analysis',), name='estados_unique_chave_analysis', violation_error_message='Chave Analysis é unico em Estados'), models.UniqueConstraint(fields=('sigla',), name='estados_unique_sigla', violation_error_message='Sigla é unico em Estados')],
            },
        ),
    ]
