# Generated by Django 5.1 on 2024-10-31 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_paises_nome_estados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_analysis', models.IntegerField(verbose_name='ID Analysis')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('chave_migracao', models.IntegerField(null=True, verbose_name='Chave Migração')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.estados', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'constraints': [models.UniqueConstraint(fields=('chave_analysis',), name='cidades_unique_chave_analysis', violation_error_message='Chave Analysis é unico em Cidades')],
            },
        ),
    ]
