# Generated by Django 5.1 on 2024-11-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_cidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidades',
            name='chave_migracao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chave Migração'),
        ),
        migrations.AlterField(
            model_name='estados',
            name='chave_migracao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chave Migração'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='chave_migracao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chave Migração'),
        ),
        migrations.AlterField(
            model_name='paises',
            name='chave_migracao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chave Migração'),
        ),
    ]
