# Generated by Django 5.1 on 2024-11-07 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_cidades_chave_migracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistentestecnicosagenda',
            name='assistente_tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.assistentestecnicos', verbose_name='Assistente Tecnico'),
        ),
        migrations.AlterField(
            model_name='cidades',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.estados', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='homelinksdocumentos',
            name='home_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='home.homelinks', verbose_name='Home Link'),
        ),
    ]
