# Generated by Django 5.1 on 2024-11-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_assistentestecnicosagenda_assistente_tecnico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'constraints': [models.UniqueConstraint(fields=('nome',), name='bancos_unique_nome', violation_error_message='Nome é unico em Banco')],
            },
        ),
    ]
