# Generated by Django 5.1 on 2024-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_bancos'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
    ]
