# Generated by Django 5.1 on 2024-11-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_jobs_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='razao_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão Social'),
        ),
    ]
