# Generated by Django 5.1 on 2024-12-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rateio_salario_adm_cp_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atualizacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('nome_funcao', models.CharField(max_length=200, verbose_name='Nome Função')),
                ('observacoes', models.CharField(max_length=300, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Atualização',
                'verbose_name_plural': 'Atualizações',
                'constraints': [models.UniqueConstraint(fields=('descricao',), name='atualizacoes_unique_descricao', violation_error_message='Descrição é campo unico')],
            },
        ),
    ]
