# Generated by Django 5.1 on 2024-12-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_atualizacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacoes',
            name='observacoes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observações'),
        ),
    ]
