# Generated by Django 5.1 on 2024-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_atualizacoes_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='atualizacoes_ano',
            field=models.IntegerField(default=2000, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='atualizacoes_ano_fim',
            field=models.IntegerField(default=2001, verbose_name='Ano Fim'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='atualizacoes_ano_inicio',
            field=models.IntegerField(default=2000, verbose_name='Ano Inicio'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='atualizacoes_data_ano_fim',
            field=models.DateField(default='2000-12-31', verbose_name='Data Ano Fim'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='atualizacoes_data_ano_inicio',
            field=models.DateField(default='2000-01-01', verbose_name='Data Ano Inicio'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='atualizacoes_data_mes_fim',
            field=models.DateField(default='2000-01-31', verbose_name='Data Mês Fim'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='atualizacoes_data_mes_inicio',
            field=models.DateField(default='2000-01-01', verbose_name='Data Mês Inicio'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='atualizacoes_mes',
            field=models.IntegerField(default=1, verbose_name='Mês'),
        ),
    ]
