# Generated by Django 5.1 on 2024-12-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_sitesetup_atualizacoes_ano_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosModelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, help_text='A imagem será redimensionada proporcionalmente para 300 px de largura', null=True, upload_to='home/produtos_modelos/%Y/%m/', verbose_name='Imagem Principal')),
            ],
            options={
                'verbose_name': 'Produtos Modelo',
                'verbose_name_plural': 'Produtos Modelos',
                'constraints': [models.UniqueConstraint(fields=('descricao',), name='modelos_unique_descricao', violation_error_message='Descrição é campo unico')],
            },
        ),
    ]
