# Generated by Django 5.1 on 2024-12-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_produtosmodelostopicos_atualizado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosModelosTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Produtos Modelos Tag',
                'verbose_name_plural': 'Produtos Modelos Tags',
                'constraints': [models.UniqueConstraint(fields=('descricao',), name='tags_unique_descricao', violation_error_message='Descrição é campo unico')],
            },
        ),
    ]
