# Generated by Django 5.1 on 2024-12-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_produtosmodelostags'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosmodelos',
            name='tags',
            field=models.ManyToManyField(related_name='%(class)s', to='home.produtosmodelostags', verbose_name='Tags'),
        ),
    ]
