# Generated by Django 5.1 on 2024-12-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_produtosmodelostopicos_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosmodelos',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', related_name='%(class)s', to='home.produtosmodelostags', verbose_name='Tags'),
        ),
    ]
