# Generated by Django 5.1 on 2024-12-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_produtosmodelos_slug_produtosmodelostags_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosmodelos',
            name='url_site',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='URL do Site'),
        ),
    ]
