# Generated by Django 5.1 on 2025-01-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_produtosmodelos_url_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_analysis', models.IntegerField(verbose_name='ID Analysis')),
                ('unidade', models.CharField(max_length=6, verbose_name='Unidade')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descrição')),
                ('chave_migracao', models.IntegerField(blank=True, null=True, verbose_name='Chave Migração')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'constraints': [models.UniqueConstraint(fields=('chave_analysis',), name='unidades_unique_chave_analysis', violation_error_message='Chave Analysis é unico em Unidades'), models.UniqueConstraint(fields=('unidade',), name='unidades_unique_unidade', violation_error_message='Unidade é unico em Unidades')],
            },
        ),
    ]
