# Generated by Django 5.1 on 2025-01-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_unidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidades',
            name='chave_migracao',
        ),
    ]
