# Generated by Django 5.1 on 2025-01-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='medida_volume_padrao_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Medida Volume Padrão X (m)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='medida_volume_padrao_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Medida Volume Padrão Y (m)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='medida_volume_padrao_z',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Medida Volume Padrão Z (m)'),
        ),
    ]
