# Generated by Django 5.1 on 2025-01-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_produtos_quantidade_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosIcms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icms', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ICMS %')),
                ('icms_frete', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ICMS Frete %')),
                ('chave_migracao', models.IntegerField(blank=True, null=True, verbose_name='Chave Migração')),
                ('uf_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_uf_destino', to='home.estados', verbose_name='UF Destino')),
                ('uf_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_uf_origem', to='home.estados', verbose_name='UF Origem')),
            ],
            options={
                'verbose_name': 'Estado ICMS',
                'verbose_name_plural': 'Estados ICMS',
                'constraints': [models.UniqueConstraint(fields=('uf_origem', 'uf_destino'), name='estadosicms_unique_uf', violation_error_message='UF Origem e Destino são unicos em Estados ICMS')],
            },
        ),
    ]
