# Generated by Django 5.1 on 2025-01-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_estadosicms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadosicms',
            name='chave_migracao',
        ),
    ]
