# Generated by Django 5.1 on 2025-01-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_alter_estadosicms_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='aliquota_icms_simples',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Aliquota ICMS Simples %'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='aliquota_pis_cofins',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Aliquota PIS / Cofins %'),
        ),
    ]
