# Generated by Django 5.1 on 2025-01-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_sitesetup_aliquota_icms_simples_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estados',
            options={'ordering': ('uf',), 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
    ]
