# Generated by Django 5.1 on 2025-01-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_alter_estados_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ('nome',), 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
