# Generated by Django 5.1 on 2025-02-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_alter_produtos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_analysis', models.IntegerField(verbose_name='ID Analysis')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'constraints': [models.UniqueConstraint(fields=('chave_analysis',), name='vendedores_unique_chave_analysis', violation_error_message='Chave Analysis é unico em Vendedores'), models.UniqueConstraint(fields=('nome',), name='vendedores_unique_nome', violation_error_message='Nome é unico em Vendedores')],
            },
        ),
    ]
