# Generated by Django 5.1 on 2025-02-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_vendedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanaisVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_analysis', models.IntegerField(verbose_name='ID Analysis')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Canal de Vendas',
                'verbose_name_plural': 'Canais de Vendas',
                'constraints': [models.UniqueConstraint(fields=('chave_analysis',), name='canais_vendas_unique_chave_analysis', violation_error_message='Chave Analysis é unico em Canais de Vendas'), models.UniqueConstraint(fields=('descricao',), name='canais_vendas_unique_descricao', violation_error_message='Descrição é unico em Canais de Vendas')],
            },
        ),
    ]
