# Generated by Django 5.1 on 2025-02-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_canaisvendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='canal_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.canaisvendas', verbose_name='Canal de Venda'),
        ),
    ]
