# Generated by Django 5.1 on 2025-02-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_vendedores_canal_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regioes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_analysis', models.IntegerField(verbose_name='ID Analysis')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
                'constraints': [models.UniqueConstraint(fields=('chave_analysis',), name='regioes_unique_chave_analysis', violation_error_message='Chave Analysis é unico em Regiões'), models.UniqueConstraint(fields=('nome',), name='regioes_unique_nome', violation_error_message='Nome é unico em Regiões')],
            },
        ),
    ]
