# Generated by Django 5.1 on 2025-02-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_estados_regiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados',
            name='regiao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.regioes', verbose_name='Região'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='canal_venda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.canaisvendas', verbose_name='Canal de Venda'),
            preserve_default=False,
        ),
    ]
