# Generated by Django 5.1 on 2025-02-19 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_alter_estados_regiao_alter_vendedores_canal_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedoresRegioes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='home.regioes', verbose_name='Região')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='home.vendedores', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Vendedor Região',
                'verbose_name_plural': 'Vendedor Regiões',
                'constraints': [models.UniqueConstraint(fields=('vendedor', 'regiao'), name='vendedores_regiao_unique', violation_error_message='Vendedor e Região são unicos em Vendedores Regiões')],
            },
        ),
    ]
