# Generated by Django 5.1 on 2025-03-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_vendedoresregioes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedoresEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='home.estados', verbose_name='Estado')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='home.vendedores', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Vendedor Estado',
                'verbose_name_plural': 'Vendedor Estados',
                'constraints': [models.UniqueConstraint(fields=('vendedor', 'estado'), name='vendedores_estado_unique', violation_error_message='Vendedor e Estado são unicos em Vendedores Estados')],
            },
        ),
    ]
