# Generated by Django 5.1 on 2025-03-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_vendedoresestados'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='meta_mes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Meta do Mês'),
        ),
    ]
