# Generated by Django 5.1 on 2025-05-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_vendedores_meta_mes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedores',
            options={'ordering': ('nome',), 'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
    ]
