# Generated by Django 5.1 on 2025-05-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_alter_vendedores_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='dias_uteis_mes_reais',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Dias Uteis Reais'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='dias_uteis_mes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Dias Uteis Considerar'),
        ),
    ]
