# Generated by Django 5.1 on 2025-06-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_sitesetup_dias_uteis_mes_reais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='despesa_administrativa_fixa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Despesa Administrativa Fixa %'),
        ),
    ]
