# Generated by Django 5.1 on 2025-07-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_jobs_despesa_administrativa_fixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='sigla',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Sigla'),
        ),
        migrations.AddConstraint(
            model_name='jobs',
            constraint=models.UniqueConstraint(fields=('sigla',), name='jobs_unique_sigla', violation_error_message='Sigla é unica em Jobs'),
        ),
    ]
