# Generated by Django 5.1 on 2025-07-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_jobs_sigla_jobs_jobs_unique_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='sigla',
            field=models.CharField(default=1, max_length=3, verbose_name='Sigla'),
            preserve_default=False,
        ),
    ]
