# Generated by Django 5.1 on 2025-07-18 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_alter_jobs_sigla'),
        ('rh', '0038_afastamentos_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.funcionarios', verbose_name='Responsavel'),
        ),
    ]
