# Generated by Django 5.1 on 2025-07-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_vendedores_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='considerar_total',
            field=models.BooleanField(default=False, verbose_name='Considerar Valores no Total'),
        ),
    ]
