# Generated by Django 5.1 on 2025-07-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_vendedores_considerar_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='atualizacoes',
            name='app',
            field=models.CharField(default='home', max_length=100, verbose_name='App'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atualizacoes',
            name='arquivo',
            field=models.CharField(default='services', max_length=100, verbose_name='Arquivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atualizacoes',
            name='gera_arquivo',
            field=models.BooleanField(default=False, verbose_name='Gera Arquivo?'),
        ),
    ]
