# Generated by Django 5.1 on 2025-07-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_atualizacoes_app_atualizacoes_arquivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleInscricoesEstaduais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_documento', models.IntegerField(verbose_name='Ultimo Orçamento Conferido')),
                ('ultima_conferencia', models.DateTimeField(verbose_name='Ultima Conferencia')),
            ],
            options={
                'verbose_name': 'Controle Inscrições Estaduais',
                'verbose_name_plural': 'Controle Inscrições Estaduais',
            },
        ),
    ]
