# Generated by Django 5.1 on 2025-07-29 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_controleinscricoesestaduais'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricoesEstaduais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('ultima_conferencia', models.DateTimeField(verbose_name='Ultima Conferencia')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.estados', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Inscrição Estadual',
                'verbose_name_plural': 'Inscrições Estaduais',
            },
        ),
    ]
