# Generated by Django 5.1 on 2025-07-29 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_inscricoesestaduais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricoesestaduais',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.estados', verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
