# Generated by Django 5.1 on 2025-10-06 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_alter_inscricoesestaduais_estado'),
        ('rh', '0039_alter_salarios_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=30, verbose_name='Status')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='rh.funcionarios', verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Responsavel',
                'verbose_name_plural': 'Responsaveis',
                'constraints': [models.UniqueConstraint(fields=('nome',), name='responsaveis_unique_nome', violation_error_message='Nome é unico em Responsaveis')],
            },
        ),
    ]
