# Generated by Django 5.1 on 2025-12-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_responsaveis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_analysis', models.IntegerField(verbose_name='ID Analysis')),
                ('sigla', models.CharField(max_length=5, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'constraints': [models.UniqueConstraint(fields=('chave_analysis',), name='fornecedores_unique_chave_analysis', violation_error_message='Chave Analysis é campo unico'), models.UniqueConstraint(fields=('sigla',), name='fornecedores_unique_sigla', violation_error_message='Sigla é campo unico')],
            },
        ),
    ]
