# Generated by Django 5.1 on 2025-12-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_fornecedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosTipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_analysis', models.IntegerField(verbose_name='ID Analysis')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Produto',
                'verbose_name_plural': 'Tipos de Produto',
                'constraints': [models.UniqueConstraint(fields=('chave_analysis',), name='produtos_tipos_unique_chave_analysis', violation_error_message='Chave Analysis é unico em Produtos Tipos'), models.UniqueConstraint(fields=('descricao',), name='produtos_tipos_unique_descricao', violation_error_message='Unidade é unico em Produtos Tipos')],
            },
        ),
    ]
