# Generated by Django 5.1 on 2025-12-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_produtostipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.produtostipos', verbose_name='Tipo'),
        ),
    ]
