# Generated by Django 5.1 on 2025-12-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_produtos_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedores',
            options={'ordering': ('sigla',), 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
