# Generated by Django 5.1 on 2025-12-18 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_alter_fornecedores_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.produtostipos', verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
