# Generated by Django 5.1 on 2026-06-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_alter_produtos_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='proporcao_meta',
            field=models.DecimalField(decimal_places=5, default=0.0, help_text='da meta definida em site setup', max_digits=8, verbose_name='Proporção Meta %'),
        ),
    ]
