# Generated by Django 5.1 on 2026-06-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_jobs_proporcao_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='proporcao_meta',
            field=models.DecimalField(decimal_places=10, default=0.0, help_text='da meta definida em site setup', max_digits=13, verbose_name='Proporção Meta %'),
        ),
    ]
