# Generated by Django 5.1 on 2026-07-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_alter_jobs_proporcao_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosFamilias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_analysis', models.IntegerField(verbose_name='ID Analysis')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Familia de Produto',
                'verbose_name_plural': 'Familias de Produto',
                'constraints': [models.UniqueConstraint(fields=('chave_analysis',), name='produtos_familias_unique_chave_analysis', violation_error_message='Chave Analysis é unico em Produtos Familias'), models.UniqueConstraint(fields=('descricao',), name='produtos_familias_unique_descricao', violation_error_message='Descrição é unico em Produtos Familias')],
            },
        ),
    ]
