# Generated by Django 5.1 on 2026-07-08 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_produtosfamilias'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.produtosfamilias', verbose_name='Familia'),
        ),
    ]
