# Generated by Django 5.1 on 2026-07-08 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_produtos_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosfamilias',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='home.jobs', verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='produtosfamilias',
            name='proporcao_meta_job',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13, verbose_name='Proporção Meta Job %'),
        ),
    ]
