# Generated by Django 5.1 on 2026-09-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_produtosfamilias_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='meta_diaria_toneladas_produzidas',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15, verbose_name='Meta Diaria Toneladas Produzidas'),
        ),
    ]
