# Generated by Django 5.1 on 2025-02-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VENDEDORES',
            fields=[
                ('CODVENDEDOR', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMERED', models.CharField(blank=True, max_length=13, null=True, verbose_name='Nome Reduzido')),
                ('INATIVO', models.CharField(blank=True, max_length=3, null=True, verbose_name='Inativo')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'managed': False,
            },
        ),
    ]
