# Generated by Django 5.1 on 2025-02-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendedores',
            table='COPLAS.VENDEDORES',
        ),
    ]
