# Generated by Django 5.1 on 2025-02-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_vendedores_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendedores',
            table='"COPLAS"."VENDEDORES"',
        ),
    ]
