# Generated by Django 5.1 on 2025-02-13 18:23

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_vendedores_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESTADOS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ESTADO', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome Reduzido')),
                ('SIGLA', models.CharField(blank=True, max_length=2, null=True, verbose_name='Inativo')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': '"COPLAS"."ESTADOS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
