# Generated by Django 5.1 on 2025-02-13 18:52

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_estados'),
    ]

    operations = [
        migrations.CreateModel(
            name='MATRIZ_ICMS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ALIQUOTA', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Aliquota %')),
            ],
            options={
                'verbose_name': 'Estado ICMS',
                'verbose_name_plural': 'Estados ICMS',
                'db_table': '"COPLAS"."MATRIZ_ICMS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
