# Generated by Django 5.1 on 2025-02-17 13:15

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_matriz_icms'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAIXAS_CEP',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('CIDADE', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inativo')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': '"COPLAS"."FAIXAS_CEP"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
