# Generated by Django 5.1 on 2025-02-17 14:47

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_faixas_cep'),
    ]

    operations = [
        migrations.CreateModel(
            name='UNIDADES',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('UNIDADE', models.CharField(blank=True, max_length=6, null=True, verbose_name='Nome Reduzido')),
                ('DESCRICAO', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inativo')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'db_table': '"COPLAS"."UNIDADES"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
