# Generated by Django 5.1 on 2025-02-17 15:08

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_unidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUTOS',
            fields=[
                ('CPROD', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO', models.CharField(blank=True, max_length=60, null=True, verbose_name='Codigo')),
                ('DESCRICAO', models.CharField(blank=True, max_length=120, null=True, verbose_name='Descrição')),
                ('PESO_LIQUIDO', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Peso Liquido')),
                ('PESO_BRUTO', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Peso Bruto')),
                ('FORA_DE_LINHA', models.CharField(blank=True, max_length=3, null=True, verbose_name='Fora de Linha')),
                ('CODIGO_BARRA', models.CharField(blank=True, max_length=13, null=True, verbose_name='Codigo de Barras (EAN13)')),
                ('CARACTERISTICA2', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Caracteristica 2')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': '"COPLAS"."PRODUTOS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
