# Generated by Django 5.1 on 2025-02-17 15:48

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAMILIA_PRODUTOS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('FAMILIA', models.CharField(blank=True, max_length=50, null=True, verbose_name='Familia')),
            ],
            options={
                'verbose_name': 'Familia Produtos',
                'verbose_name_plural': 'Familias Produtos',
                'db_table': '"COPLAS"."FAMILIA_PRODUTOS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
