# Generated by Django 5.1 on 2025-02-18 14:25

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_familia_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CANAIS_VENDA',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.CharField(blank=True, max_length=30, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Canal de Vendas',
                'verbose_name_plural': 'Canais de Vendas',
                'db_table': '"COPLAS"."CANAIS_VENDA"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
