# Generated by Django 5.1 on 2025-02-18 17:12

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_canais_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='REGIOES',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('REGIAO', models.CharField(blank=True, max_length=20, null=True, verbose_name='Região')),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
                'db_table': '"COPLAS"."REGIOES"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
