# Generated by Django 5.1 on 2025-03-18 14:29

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_regioes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENTES_TIPOS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.CharField(blank=True, max_length=20, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Clientes',
                'verbose_name_plural': 'Tipos de Clientes',
                'db_table': '"COPLAS"."CLIENTES_TIPOS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
