# Generated by Django 5.1 on 2025-03-26 13:48

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_clientes_tipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='STATUS_ORCAMENTOS_ITENS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
                ('TIPO', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Status Orçamentos Produtos',
                'verbose_name_plural': 'Status Orçamentos Produtos',
                'db_table': '"COPLAS"."STATUS_ORCAMENTOS_ITENS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
