# Generated by Django 5.1 on 2025-04-03 17:32

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_clientes_grupo_economico'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENTES_HISTORICO',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA', models.DateField(blank=True, null=True, verbose_name='Data Previsão')),
                ('DATA_REALIZADO', models.DateField(blank=True, null=True, verbose_name='Data Realizado')),
                ('ASSUNTO', models.CharField(blank=True, max_length=40, null=True, verbose_name='Assunto')),
                ('OBSERVACOES_EVENTO', models.TextField(blank=True, null=True, verbose_name='Observações Evento')),
                ('OBSERVACOES_EVENTO_FECHAMENTO', models.TextField(blank=True, null=True, verbose_name='Observações Evento Fechamento')),
            ],
            options={
                'verbose_name': 'Evento Cliente',
                'verbose_name_plural': 'Eventos Cliente',
                'db_table': '"COPLAS"."CLIENTES_HISTORICO"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TIPOS_HISTORICO',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPO', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Evento',
                'db_table': '"COPLAS"."TIPOS_HISTORICO"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='V_COLABORADORES',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('USUARIO', models.CharField(blank=True, max_length=30, null=True, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': '"COPLAS"."V_COLABORADORES"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
