# Generated by Django 5.1 on 2025-04-08 17:49

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_clientes_historico_tipos_historico_v_colaboradores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORCAMENTOS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMPED', models.IntegerField(verbose_name='Nº Orçamento')),
                ('DATA_PEDIDO', models.DateField(blank=True, null=True, verbose_name='Data Orçamento')),
                ('VALOR_TOTAL', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Valor Total')),
                ('STATUS', models.CharField(blank=True, max_length=15, null=True, verbose_name='Status')),
                ('VALOR_FRETE', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Valor Frete')),
                ('REGISTRO_OPORTUNIDADE', models.CharField(blank=True, max_length=3, null=True, verbose_name='Oportunidade')),
                ('VALOR_FRETE_EMPRESA', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Valor Frete Empresa')),
                ('FRETE_INCL_ITEM', models.CharField(blank=True, max_length=3, null=True, verbose_name='Frete Incluso nos Itens')),
                ('VALOR_FRETE_INCL_ITEM', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Valor Frete Incluso nos Itens')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'db_table': '"COPLAS"."ORCAMENTOS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PEDIDOS_TIPOS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
                ('VALOR_COMERCIAL', models.CharField(blank=True, max_length=3, null=True, verbose_name='Valor Comercial')),
            ],
            options={
                'verbose_name': 'Tipo de Pedido',
                'verbose_name_plural': 'Tipos de Pedido',
                'db_table': '"COPLAS"."PEDIDOS_TIPOS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
