# Generated by Django 5.1 on 2025-04-08 18:43

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_orcamentos_itens'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEDIDOS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMPED', models.IntegerField(verbose_name='Nº Pedido')),
                ('DATA_PEDIDO', models.DateField(blank=True, null=True, verbose_name='Data Pedido')),
                ('VALOR_TOTAL', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Valor Total')),
                ('STATUS', models.CharField(blank=True, max_length=15, null=True, verbose_name='Status')),
                ('VALOR_FRETE', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Valor Frete')),
                ('VALOR_FRETE_EMPRESA', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Valor Frete Empresa')),
                ('FRETE_INCL_ITEM', models.CharField(blank=True, max_length=3, null=True, verbose_name='Frete Incluso nos Itens')),
                ('VALOR_FRETE_INCL_ITEM', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Valor Frete Incluso nos Itens')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': '"COPLAS"."PEDIDOS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
