# Generated by Django 5.1 on 2025-04-09 14:05

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_contatos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEDIDOS_ITENS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('QUANTIDADE', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Quantidade')),
                ('DATA_ENTREGA', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('PRECO_TABELA', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Preço de Tabela')),
                ('PRECO_VENDA', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Preço de Venda')),
                ('VALOR_TOTAL', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Valor Total')),
                ('STATUS', models.CharField(blank=True, max_length=15, null=True, verbose_name='Status')),
                ('RATEIO_FRETE', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Rateio Frete')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Itens de Pedido',
                'db_table': '"COPLAS"."PEDIDOS_ITENS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
