# Generated by Django 5.1 on 2025-04-09 14:21

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_pedidos_itens'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOTAS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('NF', models.IntegerField(verbose_name='Nº Nota')),
                ('ESPECIE', models.CharField(blank=True, max_length=1, null=True, verbose_name='Especie')),
                ('DATA_EMISSAO', models.DateField(blank=True, null=True, verbose_name='Data Emissão')),
                ('VALOR_FRETE', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Valor Frete')),
                ('VALOR_MERCADORIAS', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Valor Mercadorias')),
                ('ATIVA', models.CharField(blank=True, max_length=3, null=True, verbose_name='Ativa')),
                ('VALOR_COMERCIAL', models.CharField(blank=True, max_length=3, null=True, verbose_name='Valor Comercial')),
                ('VALOR_FRETE_EMPRESA', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Valor Frete Empresa')),
                ('FRETE_INCL_ITEM', models.CharField(blank=True, max_length=3, null=True, verbose_name='Frete Incluso nos Itens')),
                ('VALOR_FRETE_INCL_ITEM', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Valor Frete Incluso nos Itens')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': '"COPLAS"."NOTAS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
