# Generated by Django 5.1 on 2025-04-09 14:43

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOTAS_ITENS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('QUANTIDADE', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Quantidade')),
                ('PRECO_TABELA', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Preço de Tabela')),
                ('PRECO_FATURADO', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Preço Faturado')),
                ('VALOR_MERCADORIAS', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Valor Mercadorias')),
                ('RATEIO_FRETE', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Rateio Frete')),
            ],
            options={
                'verbose_name': 'Item da Nota',
                'verbose_name_plural': 'Itens da Nota',
                'db_table': '"COPLAS"."NOTAS_ITENS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
