# Generated by Django 5.1 on 2025-06-05 14:01

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_notas_itens'),
    ]

    operations = [
        migrations.CreateModel(
            name='INFORMACOES_CLI',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Informação Estrategica',
                'verbose_name_plural': 'Informações Estrategicas',
                'db_table': '"COPLAS"."INFORMACOES_CLI"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
