# Generated by Django 5.1 on 2025-10-09 13:06

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0024_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRUPO_PRODUTOS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('GRUPO', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Grupo Produtos',
                'verbose_name_plural': 'Grupos Produtos',
                'db_table': '"COPLAS"."GRUPO_PRODUTOS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LINHA_PRODUTOS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('LINHA', models.CharField(blank=True, max_length=50, null=True, verbose_name='Linha')),
            ],
            options={
                'verbose_name': 'Linha Produtos',
                'verbose_name_plural': 'Linhas Produtos',
                'db_table': '"COPLAS"."LINHA_PRODUTOS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MARCAS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('MARCA', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': '"COPLAS"."MARCAS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
