# Generated by Django 5.1 on 2025-12-01 14:48

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0025_grupo_produtos_linha_produtos_marcas'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOTAS_NFE_LOG',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Log NFe Nota',
                'verbose_name_plural': 'Logs NFe Notas',
                'db_table': '"COPLAS"."NOTAS_NFE_LOG"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
