# Generated by Django 5.1 on 2025-12-11 12:15

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0026_notas_nfe_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='FORNECEDORES',
            fields=[
                ('CODFOR', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMERED', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome Reduzido')),
                ('NOME', models.CharField(blank=True, max_length=50, null=True, verbose_name='Razão Social')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': '"COPLAS"."FORNECEDORES"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
