# Generated by Django 5.1 on 2025-12-11 13:43

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0027_fornecedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='TIPO_PRODUTOS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPO', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Produto',
                'verbose_name_plural': 'Tipos de Produto',
                'db_table': '"COPLAS"."TIPO_PRODUTOS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
