# Generated by Django 5.1 on 2026-02-04 18:35

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0028_tipo_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='OC_MP',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA_EMISSAO', models.DateField(blank=True, null=True, verbose_name='Data Emissão')),
            ],
            options={
                'verbose_name': 'Ordem de Compra',
                'verbose_name_plural': 'Ordens de Compra',
                'db_table': '"COPLAS"."OC_MP"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OC_MP_ITENS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_ITEM', models.IntegerField(verbose_name='ID Item')),
                ('QUANTIDADE', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Quantidade')),
                ('DATA_ENTREGA', models.DateField(blank=True, null=True, verbose_name='Data Entrega')),
            ],
            options={
                'verbose_name': 'Ordem de Compra Item',
                'verbose_name_plural': 'Ordem de Compra Itens',
                'db_table': '"COPLAS"."OC_MP_ITENS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
