# Generated by Django 5.1 on 2026-05-20 17:47

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0029_oc_mp_oc_mp_itens'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLASSE_IPI',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('CLASSIFICACAO', models.CharField(blank=True, max_length=14, null=True, verbose_name='Classificação')),
                ('IPI', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='IPI %')),
            ],
            options={
                'verbose_name': 'NCM',
                'verbose_name_plural': 'NCMs',
                'db_table': '"COPLAS"."CLASSE_IPI"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
