# Generated by Django 5.1 on 2026-05-20 18:05

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0030_classe_ipi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUTOS_JOBS_CUSTOS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSTO_INDUSTRIAL', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Custo Industrial')),
                ('CUSTO_MEDIO_COMPRA', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Custo Compra')),
                ('CUSTO_TOTAL', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Custo Total')),
                ('DIVISOR', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Divisor')),
                ('PRECO_OBJETIVO_VISTA', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Preço Objetivo Vista')),
                ('PRECO_ICMS0', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Preço ICMS 0%')),
                ('PRECO_ICMS4', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Preço ICMS 4%')),
                ('PRECO_ICMS7', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Preço ICMS 7%')),
                ('PRECO_ICMS12', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Preço ICMS 12%')),
                ('PRECO_ICMS18', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Preço ICMS 18%')),
                ('PRECO_ICMS17', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Preço ICMS 17%')),
                ('PRECO_ICMS19', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Preço ICMS 19%')),
            ],
            options={
                'verbose_name': 'Custo de Produto por Job',
                'verbose_name_plural': 'Custos de Produtos por jobs',
                'db_table': '"COPLAS"."PRODUTOS_JOBS_CUSTOS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
