# Generated by Django 5.1 on 2026-05-28 17:46

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0031_produtos_jobs_custos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PARADAS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO', models.IntegerField(verbose_name='Codigo')),
                ('DESCRICAO', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'db_table': '"COPLAS"."PARADAS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
