# Generated by Django 5.1 on 2026-05-28 18:34

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0032_paradas'),
    ]

    operations = [
        migrations.CreateModel(
            name='APONTAMENTOS_PARADAS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('OBSERVACOES', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações')),
                ('INICIO', models.DateTimeField(blank=True, null=True, verbose_name='Inicio')),
                ('TERMINO', models.DateTimeField(blank=True, null=True, verbose_name='Termino')),
                ('TEMPO', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Tempo')),
            ],
            options={
                'verbose_name': 'Ordem de Compra Item',
                'verbose_name_plural': 'Ordem de Compra Itens',
                'db_table': '"COPLAS"."APONTAMENTOS_PARADAS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
