# Generated by Django 5.1 on 2026-07-30 14:08

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0033_apontamentos_paradas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAQUINAS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO', models.CharField(blank=True, max_length=12, null=True, verbose_name='Codigo')),
                ('DESCRICAO', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Maquina',
                'verbose_name_plural': 'Maquinas',
                'db_table': '"COPLAS"."MAQUINAS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
