# Generated by Django 5.1 on 2026-07-30 14:13

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_maquinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOLDES',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO', models.CharField(blank=True, max_length=15, null=True, verbose_name='Codigo')),
                ('DESCRICAO', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
                ('CAVIDADES', models.IntegerField(verbose_name='Cavidades')),
            ],
            options={
                'verbose_name': 'Molde',
                'verbose_name_plural': 'Moldes',
                'db_table': '"COPLAS"."MOLDES"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
