# Generated by Django 5.1 on 2026-07-30 14:16

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_moldes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOLDES_MAQUINAS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Molde Maquinas',
                'verbose_name_plural': 'Moldes Maquinas',
                'db_table': '"COPLAS"."MOLDES_MAQUINAS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
