# Generated by Django 5.1 on 2026-07-30 14:47

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0036_moldes_maquinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROCESSOS',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO', models.CharField(blank=True, max_length=60, null=True, verbose_name='Codigo')),
                ('PADRAO', models.CharField(blank=True, max_length=3, null=True, verbose_name='Padrão')),
                ('FORA_LINHA', models.CharField(blank=True, max_length=3, null=True, verbose_name='Fora de Linha')),
                ('DESCRICAO_PROCESSO', models.CharField(blank=True, max_length=120, null=True, verbose_name='Descrição Processo')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'db_table': '"COPLAS"."PROCESSOS"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
