# Generated by Django 5.1 on 2026-07-30 14:51

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0037_processos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUSTOS_SETORES',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME_SETOR', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome Setor')),
            ],
            options={
                'verbose_name': 'Setor de Custos',
                'verbose_name_plural': 'Setores de Custos',
                'db_table': '"COPLAS"."CUSTOS_SETORES"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
