# Generated by Django 5.1 on 2026-07-30 15:17

import utils.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0038_custos_setores'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROCESSOS_OPERACOES',
            fields=[
                ('CHAVE', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDEM', models.IntegerField(verbose_name='Ordem')),
                ('CICLO', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Ciclo')),
                ('TEMPO_TOTAL', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Tempo Total')),
                ('PECAS_MINUTO', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True, verbose_name='Peças / Minuto')),
                ('DESCRICAO', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Operação Processo',
                'verbose_name_plural': 'Operações Processos',
                'db_table': '"COPLAS"."PROCESSOS_OPERACOES"',
                'managed': False,
            },
            bases=(utils.base_models.ReadOnlyMixin, models.Model),
        ),
    ]
