pedidos = """
    SELECT
        EXTRACT(MONTH FROM PEDIDOS.DATA_PEDIDO) AS MES,
        VENDEDORES.NOMERED AS CARTEIRA,
        PEDIDOS.NUMPED,
        PEDIDOS.CHAVE AS CHAVE_PEDIDO,
        PEDIDOS_ITENS.CHAVE AS CHAVE_PEDIDO_ITEM,
        PRODUTOS.CHAVE_FAMILIA,
        PRODUTOS.CODIGO,
        ROUND(PEDIDOS_ITENS.VALOR_TOTAL - (PEDIDOS_ITENS.PESO_LIQUIDO / PEDIDOS.PESO_LIQUIDO * PEDIDOS.VALOR_FRETE_INCL_ITEM), 2) AS VALOR_MERCADORIAS,
        ROUND(PEDIDOS_ITENS.ANALISE_LUCRO - (PEDIDOS_ITENS.PESO_LIQUIDO / PEDIDOS.PESO_LIQUIDO * PEDIDOS.VALOR_FRETE_INCL_ITEM), 2) AS MC,
        ROUND(PEDIDOS_ITENS.RATEIO_FRETE + (PEDIDOS_ITENS.PESO_LIQUIDO / PEDIDOS.PESO_LIQUIDO * PEDIDOS.VALOR_FRETE_INCL_ITEM), 2) AS RATEIO_FRETE,
        ROUND((PEDIDOS_ITENS.RATEIO_FRETE + (PEDIDOS_ITENS.PESO_LIQUIDO / PEDIDOS.PESO_LIQUIDO * PEDIDOS.VALOR_FRETE_INCL_ITEM)) * PEDIDOS_ITENS.ALIQUOTA_IPI / 100, 2) AS IPI,
        ROUND((PEDIDOS_ITENS.RATEIO_FRETE + (PEDIDOS_ITENS.PESO_LIQUIDO / PEDIDOS.PESO_LIQUIDO * PEDIDOS.VALOR_FRETE_INCL_ITEM)) * (CASE WHEN PEDIDOS_ITENS.ANALISE_PIS = 0 THEN 0 ELSE 0.65 END * (1 - (PEDIDOS_ITENS.ICMS_ALIQUOTA * CASE WHEN PEDIDOS_ITENS.DESTINO_MERCADORIAS != 'CONSUMO' THEN 1 ELSE 1 + PEDIDOS_ITENS.ALIQUOTA_IPI / 100 END / 100))) / 100, 2) AS PIS,
        ROUND((PEDIDOS_ITENS.RATEIO_FRETE + (PEDIDOS_ITENS.PESO_LIQUIDO / PEDIDOS.PESO_LIQUIDO * PEDIDOS.VALOR_FRETE_INCL_ITEM)) * (CASE WHEN PEDIDOS_ITENS.ANALISE_COFINS = 0 THEN 0 ELSE 3 END * (1 - (PEDIDOS_ITENS.ICMS_ALIQUOTA * CASE WHEN PEDIDOS_ITENS.DESTINO_MERCADORIAS != 'CONSUMO' THEN 1 ELSE 1 + PEDIDOS_ITENS.ALIQUOTA_IPI / 100 END / 100))) / 100, 2) AS COFINS,
        ROUND((PEDIDOS_ITENS.RATEIO_FRETE + (PEDIDOS_ITENS.PESO_LIQUIDO / PEDIDOS.PESO_LIQUIDO * PEDIDOS.VALOR_FRETE_INCL_ITEM)) * (PEDIDOS_ITENS.ICMS_ALIQUOTA + CASE WHEN CLIENTES.ISENTO_INSCRICAO = 'SIM' AND PEDIDOS_ITENS.DESTINO_MERCADORIAS = 'CONSUMO' THEN (SELECT ALIQUOTA_FCP FROM COPLAS.MATRIZ_ICMS WHERE UF_EMITENTE = UF_DESTINO AND UF_EMITENTE = COALESCE(PLATAFORMAS.UF_ENT, CLIENTES.UF)) ELSE 0 END + CASE WHEN PEDIDOS_ITENS.ANALISE_ICMS_PARTILHA = 0 THEN 0 ELSE (SELECT ALIQUOTA FROM COPLAS.MATRIZ_ICMS WHERE UF_EMITENTE = UF_DESTINO AND UF_EMITENTE = COALESCE(PLATAFORMAS.UF_ENT, CLIENTES.UF)) - PEDIDOS_ITENS.ICMS_ALIQUOTA END) * CASE WHEN PEDIDOS_ITENS.DESTINO_MERCADORIAS != 'CONSUMO' THEN 1 ELSE 1 + PEDIDOS_ITENS.ALIQUOTA_IPI / 100 END / 100, 2) AS ICMS,
        ROUND((PEDIDOS_ITENS.RATEIO_FRETE + (PEDIDOS_ITENS.PESO_LIQUIDO / PEDIDOS.PESO_LIQUIDO * PEDIDOS.VALOR_FRETE_INCL_ITEM)) * CASE WHEN PEDIDOS_ITENS.ANALISE_CONTRIBUICAO = 0 THEN 0 ELSE 2 END / 100, 2) AS IR,
        ROUND((PEDIDOS_ITENS.RATEIO_FRETE + (PEDIDOS_ITENS.PESO_LIQUIDO / PEDIDOS.PESO_LIQUIDO * PEDIDOS.VALOR_FRETE_INCL_ITEM)) * CASE WHEN PEDIDOS_ITENS.ANALISE_CONTRIBUICAO = 0 THEN 0 ELSE 1.08 END / 100, 2) AS CSLL,
        ROUND(CASE WHEN PEDIDOS.VALOR_FRETE_INCL_ITEM = 0 THEN 0 ELSE (PEDIDOS_ITENS.PESO_LIQUIDO / PEDIDOS.PESO_LIQUIDO * PEDIDOS.VALOR_FRETE_INCL_ITEM) * PEDIDOS_ITENS.COMISSAO_PADRAO_PERC / 100 END, 2) AS COMISSAO_FRETE_ITEM,
        ROUND(CASE WHEN PEDIDOS.VALOR_FRETE_INCL_ITEM = 0 THEN 0 ELSE (PEDIDOS_ITENS.PESO_LIQUIDO / PEDIDOS.PESO_LIQUIDO * PEDIDOS.VALOR_FRETE_INCL_ITEM) * PEDIDOS_ITENS.ANALISE_DESPESAS_ADM / PEDIDOS_ITENS.VALOR_TOTAL END, 2) AS DESPESA_ADM_FRETE_ITEM,
        ROUND(CASE WHEN PEDIDOS.VALOR_FRETE_INCL_ITEM = 0 THEN 0 ELSE (PEDIDOS_ITENS.PESO_LIQUIDO / PEDIDOS.PESO_LIQUIDO * PEDIDOS.VALOR_FRETE_INCL_ITEM) * PEDIDOS_ITENS.ANALISE_DESPESAS_COM / PEDIDOS_ITENS.VALOR_TOTAL END, 2) AS DESPESA_COM_FRETE_ITEM

    FROM
        COPLAS.PLATAFORMAS,
        COPLAS.CLIENTES,
        COPLAS.VENDEDORES,
        COPLAS.PRODUTOS,
        COPLAS.PEDIDOS_ITENS,
        COPLAS.PEDIDOS

    WHERE
        PEDIDOS.CHAVE_PLATAFORMA = PLATAFORMAS.CHAVE(+) AND
        CLIENTES.CODCLI = PEDIDOS.CHAVE_CLIENTE AND
        CLIENTES.CHAVE_VENDEDOR3 = VENDEDORES.CODVENDEDOR AND
        PRODUTOS.CPROD = PEDIDOS_ITENS.CHAVE_PRODUTO AND
        PEDIDOS.CHAVE = PEDIDOS_ITENS.CHAVE_PEDIDO AND
        PEDIDOS.CHAVE_TIPO IN (SELECT CHAVE FROM COPLAS.PEDIDOS_TIPOS WHERE VALOR_COMERCIAL = 'SIM')
"""

notas = """
    SELECT
        EXTRACT(MONTH FROM NOTAS.DATA_EMISSAO) AS MES,
        VENDEDORES.NOMERED AS CARTEIRA,
        NOTAS.NF,
        NOTAS.CHAVE AS CHAVE_NOTA,
        NOTAS_ITENS.CHAVE AS CHAVE_NOTA_ITEM,
        PRODUTOS.CHAVE_FAMILIA,
        PRODUTOS.CODIGO,
        NOTAS_ITENS.VALOR_MERCADORIAS - ROUND(NOTAS_ITENS.PESO_LIQUIDO / NOTAS_PESO_LIQUIDO.PESO_LIQUIDO * NOTAS.VALOR_FRETE_INCL_ITEM, 2) AS VALOR_MERCADORIAS,
        ROUND(NOTAS_ITENS.ANALISE_LUCRO, 2) - ROUND(NOTAS_ITENS.PESO_LIQUIDO / NOTAS_PESO_LIQUIDO.PESO_LIQUIDO * NOTAS.VALOR_FRETE_INCL_ITEM, 2) AS MC,
        NOTAS_ITENS.RATEIO_FRETE + ROUND(NOTAS_ITENS.PESO_LIQUIDO / NOTAS_PESO_LIQUIDO.PESO_LIQUIDO * NOTAS.VALOR_FRETE_INCL_ITEM, 2) AS RATEIO_FRETE,
        ROUND((NOTAS_ITENS.RATEIO_FRETE + ROUND(NOTAS_ITENS.PESO_LIQUIDO / NOTAS_PESO_LIQUIDO.PESO_LIQUIDO * NOTAS.VALOR_FRETE_INCL_ITEM, 2)) * NOTAS_ITENS.IPI_ALIQUOTA / 100, 2) AS IPI,
        (NOTAS_ITENS.RATEIO_FRETE + ROUND(NOTAS_ITENS.PESO_LIQUIDO / NOTAS_PESO_LIQUIDO.PESO_LIQUIDO * NOTAS.VALOR_FRETE_INCL_ITEM, 2)) * (CASE WHEN NOTAS_ITENS.ANALISE_PIS = 0 THEN 0 ELSE 0.65 END * (1 - (NOTAS_ITENS.ICMS_ALIQUOTA * CASE WHEN NOTAS_ITENS.DESTINO_MERCADORIAS != 'CONSUMO' THEN 1 ELSE (1 + (NOTAS_ITENS.IPI_ALIQUOTA / 100)) END / 100))) / 100 AS PIS,
        (NOTAS_ITENS.RATEIO_FRETE + ROUND(NOTAS_ITENS.PESO_LIQUIDO / NOTAS_PESO_LIQUIDO.PESO_LIQUIDO * NOTAS.VALOR_FRETE_INCL_ITEM, 2)) * (CASE WHEN NOTAS_ITENS.ANALISE_COFINS = 0 THEN 0 ELSE 3 END * (1 - (NOTAS_ITENS.ICMS_ALIQUOTA * CASE WHEN NOTAS_ITENS.DESTINO_MERCADORIAS != 'CONSUMO' THEN 1 ELSE (1 + (NOTAS_ITENS.IPI_ALIQUOTA / 100)) END / 100))) / 100 AS COFINS,
        (NOTAS_ITENS.RATEIO_FRETE + ROUND(NOTAS_ITENS.PESO_LIQUIDO / NOTAS_PESO_LIQUIDO.PESO_LIQUIDO * NOTAS.VALOR_FRETE_INCL_ITEM, 2)) * (NOTAS_ITENS.ICMS_ALIQUOTA + CASE WHEN CLIENTES.ISENTO_INSCRICAO = 'SIM' AND NOTAS_ITENS.DESTINO_MERCADORIAS = 'CONSUMO' THEN (SELECT ALIQUOTA_FCP FROM COPLAS.MATRIZ_ICMS WHERE UF_EMITENTE = UF_DESTINO AND UF_EMITENTE = COALESCE(PLATAFORMAS.UF_ENT, CLIENTES.UF)) ELSE 0 END + CASE WHEN NOTAS_ITENS.ANALISE_ICMS_PARTILHA = 0 THEN 0 ELSE (SELECT ALIQUOTA FROM COPLAS.MATRIZ_ICMS WHERE UF_EMITENTE = UF_DESTINO AND UF_EMITENTE = COALESCE(PLATAFORMAS.UF_ENT, CLIENTES.UF)) - NOTAS_ITENS.ICMS_ALIQUOTA END) * CASE WHEN NOTAS_ITENS.DESTINO_MERCADORIAS != 'CONSUMO' THEN 1 ELSE (1 + (NOTAS_ITENS.IPI_ALIQUOTA / 100)) END / 100 AS ICMS,
        (NOTAS_ITENS.RATEIO_FRETE + ROUND(NOTAS_ITENS.PESO_LIQUIDO / NOTAS_PESO_LIQUIDO.PESO_LIQUIDO * NOTAS.VALOR_FRETE_INCL_ITEM, 2)) * CASE WHEN NOTAS_ITENS.ANALISE_CONTRIBUICAO = 0 THEN 0 ELSE 2 END / 100 AS IR,
        (NOTAS_ITENS.RATEIO_FRETE + ROUND(NOTAS_ITENS.PESO_LIQUIDO / NOTAS_PESO_LIQUIDO.PESO_LIQUIDO * NOTAS.VALOR_FRETE_INCL_ITEM, 2)) * CASE WHEN NOTAS_ITENS.ANALISE_CONTRIBUICAO = 0 THEN 0 ELSE 1.08 END / 100 AS CSLL,
        CASE WHEN NOTAS.VALOR_FRETE_INCL_ITEM = 0 THEN 0 ELSE ROUND(NOTAS_ITENS.PESO_LIQUIDO / NOTAS_PESO_LIQUIDO.PESO_LIQUIDO * NOTAS.VALOR_FRETE_INCL_ITEM, 2) * NOTAS_ITENS.COMISSAO_PADRAO_PERC / 100 END AS COMISSAO_FRETE_ITEM,
        CASE WHEN NOTAS.VALOR_FRETE_INCL_ITEM = 0 THEN 0 ELSE ROUND(NOTAS_ITENS.PESO_LIQUIDO / NOTAS_PESO_LIQUIDO.PESO_LIQUIDO * NOTAS.VALOR_FRETE_INCL_ITEM, 2) * NOTAS_ITENS.ANALISE_DESPESAS_ADM / NOTAS_ITENS.VALOR_MERCADORIAS END AS DESPESA_ADM_FRETE_ITEM,
        CASE WHEN NOTAS.VALOR_FRETE_INCL_ITEM = 0 THEN 0 ELSE ROUND(NOTAS_ITENS.PESO_LIQUIDO / NOTAS_PESO_LIQUIDO.PESO_LIQUIDO * NOTAS.VALOR_FRETE_INCL_ITEM, 2) * NOTAS_ITENS.ANALISE_DESPESAS_COM / NOTAS_ITENS.VALOR_MERCADORIAS END AS DESPESA_COM_FRETE_ITEM

    FROM
        (
            SELECT
                CHAVE_NOTA,
                SUM(PESO_LIQUIDO) AS PESO_LIQUIDO

            FROM
                COPLAS.NOTAS_ITENS

            GROUP BY
                CHAVE_NOTA
        ) NOTAS_PESO_LIQUIDO,
        COPLAS.PLATAFORMAS,
        COPLAS.CLIENTES,
        COPLAS.VENDEDORES,
        COPLAS.PRODUTOS,
        COPLAS.NOTAS_ITENS,
        COPLAS.NOTAS

    WHERE
        NOTAS.CHAVE = NOTAS_PESO_LIQUIDO.CHAVE_NOTA(+) AND
        NOTAS.CHAVE_PLATAFORMA = PLATAFORMAS.CHAVE(+) AND
        CLIENTES.CODCLI = NOTAS.CHAVE_CLIENTE AND
        CLIENTES.CHAVE_VENDEDOR3 = VENDEDORES.CODVENDEDOR AND
        PRODUTOS.CPROD = NOTAS_ITENS.CHAVE_PRODUTO AND
        NOTAS.CHAVE = NOTAS_ITENS.CHAVE_NOTA AND
        PRODUTOS.CHAVE_FAMILIA IN (7766, 7767, 8378, 12441) AND
        NOTAS.VALOR_COMERCIAL = 'SIM'
"""

orcamentos = """
    SELECT
        EXTRACT(MONTH FROM ORCAMENTOS.DATA_PEDIDO) AS MES,
        VENDEDORES.NOMERED AS CARTEIRA,
        ORCAMENTOS.NUMPED,
        ORCAMENTOS.CHAVE AS CHAVE_ORCAMENTO,
        ORCAMENTOS_ITENS.CHAVE AS CHAVE_ORCAMENTO_ITEM,
        PRODUTOS.CHAVE_FAMILIA,
        PRODUTOS.CODIGO,
        ROUND(ORCAMENTOS_ITENS.VALOR_TOTAL - (ORCAMENTOS_ITENS.PESO_LIQUIDO / ORCAMENTOS.PESO_LIQUIDO * ORCAMENTOS.VALOR_FRETE_INCL_ITEM), 2) AS VALOR_MERCADORIAS,
        ROUND(ORCAMENTOS_ITENS.ANALISE_LUCRO - (ORCAMENTOS_ITENS.PESO_LIQUIDO / ORCAMENTOS.PESO_LIQUIDO * ORCAMENTOS.VALOR_FRETE_INCL_ITEM), 2) AS MC,
        ROUND(ORCAMENTOS_ITENS.RATEIO_FRETE + (ORCAMENTOS_ITENS.PESO_LIQUIDO / ORCAMENTOS.PESO_LIQUIDO * ORCAMENTOS.VALOR_FRETE_INCL_ITEM), 2) AS RATEIO_FRETE,
        ROUND((ORCAMENTOS_ITENS.RATEIO_FRETE + (ORCAMENTOS_ITENS.PESO_LIQUIDO / ORCAMENTOS.PESO_LIQUIDO * ORCAMENTOS.VALOR_FRETE_INCL_ITEM)) * ORCAMENTOS_ITENS.ALIQUOTA_IPI / 100, 2) AS IPI,
        ROUND((ORCAMENTOS_ITENS.RATEIO_FRETE + (ORCAMENTOS_ITENS.PESO_LIQUIDO / ORCAMENTOS.PESO_LIQUIDO * ORCAMENTOS.VALOR_FRETE_INCL_ITEM)) * (CASE WHEN ORCAMENTOS_ITENS.ANALISE_PIS = 0 THEN 0 ELSE 0.65 END * (1 - (ORCAMENTOS_ITENS.ALIQUOTA_ICMS * CASE WHEN ORCAMENTOS_ITENS.DESTINO_MERCADORIAS != 'CONSUMO' THEN 1 ELSE 1 + ORCAMENTOS_ITENS.ALIQUOTA_IPI / 100 END / 100))) / 100, 2) AS PIS,
        ROUND((ORCAMENTOS_ITENS.RATEIO_FRETE + (ORCAMENTOS_ITENS.PESO_LIQUIDO / ORCAMENTOS.PESO_LIQUIDO * ORCAMENTOS.VALOR_FRETE_INCL_ITEM)) * (CASE WHEN ORCAMENTOS_ITENS.ANALISE_COFINS = 0 THEN 0 ELSE 3 END * (1 - (ORCAMENTOS_ITENS.ALIQUOTA_ICMS * CASE WHEN ORCAMENTOS_ITENS.DESTINO_MERCADORIAS != 'CONSUMO' THEN 1 ELSE 1 + ORCAMENTOS_ITENS.ALIQUOTA_IPI / 100 END / 100))) / 100, 2) AS COFINS,
        ROUND((ORCAMENTOS_ITENS.RATEIO_FRETE + (ORCAMENTOS_ITENS.PESO_LIQUIDO / ORCAMENTOS.PESO_LIQUIDO * ORCAMENTOS.VALOR_FRETE_INCL_ITEM)) * (ORCAMENTOS_ITENS.ALIQUOTA_ICMS + CASE WHEN CLIENTES.ISENTO_INSCRICAO = 'SIM' AND ORCAMENTOS_ITENS.DESTINO_MERCADORIAS = 'CONSUMO' THEN (SELECT ALIQUOTA_FCP FROM COPLAS.MATRIZ_ICMS WHERE UF_EMITENTE = UF_DESTINO AND UF_EMITENTE = COALESCE(PLATAFORMAS.UF_ENT, CLIENTES.UF)) ELSE 0 END + CASE WHEN ORCAMENTOS_ITENS.ANALISE_ICMS_PARTILHA = 0 THEN 0 ELSE (SELECT ALIQUOTA FROM COPLAS.MATRIZ_ICMS WHERE UF_EMITENTE = UF_DESTINO AND UF_EMITENTE = COALESCE(PLATAFORMAS.UF_ENT, CLIENTES.UF)) - ORCAMENTOS_ITENS.ALIQUOTA_ICMS END) * CASE WHEN ORCAMENTOS_ITENS.DESTINO_MERCADORIAS != 'CONSUMO' THEN 1 ELSE 1 + ORCAMENTOS_ITENS.ALIQUOTA_IPI / 100 END / 100, 2) AS ICMS,
        ROUND((ORCAMENTOS_ITENS.RATEIO_FRETE + (ORCAMENTOS_ITENS.PESO_LIQUIDO / ORCAMENTOS.PESO_LIQUIDO * ORCAMENTOS.VALOR_FRETE_INCL_ITEM)) * CASE WHEN ORCAMENTOS_ITENS.ANALISE_CONTRIBUICAO = 0 THEN 0 ELSE 2 END / 100, 2) AS IR,
        ROUND((ORCAMENTOS_ITENS.RATEIO_FRETE + (ORCAMENTOS_ITENS.PESO_LIQUIDO / ORCAMENTOS.PESO_LIQUIDO * ORCAMENTOS.VALOR_FRETE_INCL_ITEM)) * CASE WHEN ORCAMENTOS_ITENS.ANALISE_CONTRIBUICAO = 0 THEN 0 ELSE 1.08 END / 100, 2) AS CSLL,
        ROUND(CASE WHEN ORCAMENTOS.VALOR_FRETE_INCL_ITEM = 0 THEN 0 ELSE (ORCAMENTOS_ITENS.PESO_LIQUIDO / ORCAMENTOS.PESO_LIQUIDO * ORCAMENTOS.VALOR_FRETE_INCL_ITEM) * ORCAMENTOS_ITENS.COMISSAO_PADRAO_PERC / 100 END, 2) AS COMISSAO_FRETE_ITEM,
        ROUND(CASE WHEN ORCAMENTOS.VALOR_FRETE_INCL_ITEM = 0 THEN 0 ELSE (ORCAMENTOS_ITENS.PESO_LIQUIDO / ORCAMENTOS.PESO_LIQUIDO * ORCAMENTOS.VALOR_FRETE_INCL_ITEM) * ORCAMENTOS_ITENS.ANALISE_DESPESAS_ADM / ORCAMENTOS_ITENS.VALOR_TOTAL END, 2) AS DESPESA_ADM_FRETE_ITEM,
        ROUND(CASE WHEN ORCAMENTOS.VALOR_FRETE_INCL_ITEM = 0 THEN 0 ELSE (ORCAMENTOS_ITENS.PESO_LIQUIDO / ORCAMENTOS.PESO_LIQUIDO * ORCAMENTOS.VALOR_FRETE_INCL_ITEM) * ORCAMENTOS_ITENS.ANALISE_DESPESAS_COM / ORCAMENTOS_ITENS.VALOR_TOTAL END, 2) AS DESPESA_COM_FRETE_ITEM

    FROM
        COPLAS.PLATAFORMAS,
        COPLAS.CLIENTES,
        COPLAS.VENDEDORES,
        COPLAS.PRODUTOS,
        COPLAS.ORCAMENTOS_ITENS,
        COPLAS.ORCAMENTOS

    WHERE
        ORCAMENTOS.CHAVE_PLATAFORMA = PLATAFORMAS.CHAVE(+) AND
        CLIENTES.CODCLI = ORCAMENTOS.CHAVE_CLIENTE AND
        CLIENTES.CHAVE_VENDEDOR3 = VENDEDORES.CODVENDEDOR AND
        PRODUTOS.CPROD = ORCAMENTOS_ITENS.CHAVE_PRODUTO AND
        ORCAMENTOS.CHAVE = ORCAMENTOS_ITENS.CHAVE_PEDIDO AND
        ORCAMENTOS.CHAVE_TIPO IN (SELECT CHAVE FROM COPLAS.PEDIDOS_TIPOS WHERE VALOR_COMERCIAL = 'SIM')
"""
